<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE master [
  <!ELEMENT master (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (nom?,type?,ID?)+>
  <!ELEMENT nom (#PCDATA)>
  <!ELEMENT type (#PCDATA)>
  <!ELEMENT ID (#PCDATA)>
]>
<master>
  <DATA_RECORD>
    <nom>Adrien, Veuve Timothée</nom>
    <type>P</type>
    <ID>P17</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Aigron, Demoiselle</nom>
    <type>P</type>
    <ID>P25</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Albert, Jean</nom>
    <type>P</type>
    <ID>P33</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Aldin, Jean (alias Alding)</nom>
    <type>P</type>
    <ID>P35</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Alizeau, François</nom>
    <type>P</type>
    <ID>P40</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Allain, Pierre</nom>
    <type>P</type>
    <ID>P44</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Allaire Dubeignon, Henry</nom>
    <type>P</type>
    <ID>P46</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Allaire, Louis</nom>
    <type>P</type>
    <ID>P49</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Allard</nom>
    <type>P</type>
    <ID>P51</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Alvarez</nom>
    <type>P</type>
    <ID>P67</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Amoreux</nom>
    <type>P</type>
    <ID>P84</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Anceau</nom>
    <type>P</type>
    <ID>P88</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>André</nom>
    <type>P</type>
    <ID>P93</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Aniaba, prince d'Assinie</nom>
    <type>P</type>
    <ID>P100</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Apoil</nom>
    <type>P</type>
    <ID>P108</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Ardouin</nom>
    <type>P</type>
    <ID>P120</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Argenton</nom>
    <type>P</type>
    <ID>P123</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Argoud</nom>
    <type>P</type>
    <ID>P126</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Arnaud</nom>
    <type>P</type>
    <ID>P130</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Arnaudin</nom>
    <type>P</type>
    <ID>P138</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Arnoul</nom>
    <type>P</type>
    <ID>P143</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Astier (alias Hastier)</nom>
    <type>P</type>
    <ID>P158</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Astruc</nom>
    <type>P</type>
    <ID>P160</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Aubouin</nom>
    <type>P</type>
    <ID>P176</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Aubry, Marie-Françoise</nom>
    <type>P</type>
    <ID>P180</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Audebert (alias Audibert) de la Morinière, Théophile</nom>
    <type>P</type>
    <ID>P183</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Audet</nom>
    <type>P</type>
    <ID>P184</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Audureau</nom>
    <type>P</type>
    <ID>P197</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Auger</nom>
    <type>P</type>
    <ID>P201</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Ausourd, Jean</nom>
    <type>P</type>
    <ID>P221</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Aynesy</nom>
    <type>P</type>
    <ID>P240</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Baatz, Charles de</nom>
    <type>P</type>
    <ID>P243</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Babin, Elie</nom>
    <type>P</type>
    <ID>P254</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bacher, Charles</nom>
    <type>P</type>
    <ID>P263</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bagneux, Sieur de</nom>
    <type>P</type>
    <ID>P267</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Baguet</nom>
    <type>P</type>
    <ID>P269</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bailleul, Sieur de</nom>
    <type>P</type>
    <ID>P274</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Balan</nom>
    <type>P</type>
    <ID>P281</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Balon</nom>
    <type>P</type>
    <ID>P291</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Banville, Sieur de</nom>
    <type>P</type>
    <ID>P297</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Baptiste</nom>
    <type>P</type>
    <ID>P299</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Baragué</nom>
    <type>P</type>
    <ID>P301</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Barail (alias Barrail, Barrailh)</nom>
    <type>P</type>
    <ID>P302</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Barault (alias Bareau)</nom>
    <type>P</type>
    <ID>P316</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Barbaut, Jacques</nom>
    <type>P</type>
    <ID>P319</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Barbaut, Marianne</nom>
    <type>P</type>
    <ID>P320</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Barbeau</nom>
    <type>P</type>
    <ID>P325</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Barbeau des conches</nom>
    <type>P</type>
    <ID>P326</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Barber</nom>
    <type>P</type>
    <ID>P329</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Barbesieux, Louis-François-Marie Le Tellier</nom>
    <type>P</type>
    <ID>P331</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Barbot</nom>
    <type>P</type>
    <ID>P338</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Barcanon</nom>
    <type>P</type>
    <ID>P345</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bardet de Boisneau</nom>
    <type>P</type>
    <ID>P349</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bardet, Demoiselle</nom>
    <type>P</type>
    <ID>P351</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bardreau</nom>
    <type>P</type>
    <ID>P359</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Baroil</nom>
    <type>P</type>
    <ID>P372</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Baroire, le président de</nom>
    <type>P</type>
    <ID>P373</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Barreau</nom>
    <type>P</type>
    <ID>P388</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bart</nom>
    <type>P</type>
    <ID>P407</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bassemaison</nom>
    <type>P</type>
    <ID>P413</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Basset</nom>
    <type>P</type>
    <ID>P414</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bastet</nom>
    <type>P</type>
    <ID>P421</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Basville, Nicolas de Lamoignon</nom>
    <type>P</type>
    <ID>P425</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Baubriant (alias Baubriand)</nom>
    <type>P</type>
    <ID>P431</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bauché, Blaise</nom>
    <type>P</type>
    <ID>P434</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Baudin</nom>
    <type>P</type>
    <ID>P438</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Baudouin</nom>
    <type>P</type>
    <ID>P444</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Baudran</nom>
    <type>P</type>
    <ID>P449</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Baudré</nom>
    <type>P</type>
    <ID>P455</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Baugier, Edmé-Antoine</nom>
    <type>P</type>
    <ID>P459</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Baurie</nom>
    <type>P</type>
    <ID>P468</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Beat, Isaac</nom>
    <type>P</type>
    <ID>P477</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Beaubriand-Levêque, Sieur de</nom>
    <type>P</type>
    <ID>P480</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Beauharnais, de</nom>
    <type>P</type>
    <ID>P508</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Beaujeu, Le chevalier de</nom>
    <type>P</type>
    <ID>P517</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Beaulieu</nom>
    <type>P</type>
    <ID>P521</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Beaumont, Sieur de</nom>
    <type>P</type>
    <ID>P537</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Beauregard</nom>
    <type>P</type>
    <ID>P544</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Beaurepaire, Sieur de</nom>
    <type>P</type>
    <ID>P551</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Beauvais, Sieur de</nom>
    <type>P</type>
    <ID>P564</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Beccancourt, Le chevalier de</nom>
    <type>P</type>
    <ID>P577</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Béchet</nom>
    <type>P</type>
    <ID>P1498</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Béchet, les frères</nom>
    <type>P</type>
    <ID>P1501</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bégon, Michel</nom>
    <type>P</type>
    <ID>P1510</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Belcier</nom>
    <type>P</type>
    <ID>P595</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bellair, Sieur de</nom>
    <type>P</type>
    <ID>P610</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Belle-Isle, Sieur de</nom>
    <type>P</type>
    <ID>P614</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bellefonds</nom>
    <type>P</type>
    <ID>P618</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bellefonds, Sieur de</nom>
    <type>P</type>
    <ID>P620</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bellinzani</nom>
    <type>P</type>
    <ID>P633</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bellisle Errard, Sieur de</nom>
    <type>P</type>
    <ID>P637</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bellisle, Sieur de</nom>
    <type>P</type>
    <ID>P640</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Belmont, de</nom>
    <type>P</type>
    <ID>P655</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Belon</nom>
    <type>P</type>
    <ID>P659</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Belot-Lamoureux</nom>
    <type>P</type>
    <ID>P665</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bennes, Sieur de</nom>
    <type>P</type>
    <ID>P680</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Béraud</nom>
    <type>P</type>
    <ID>P1529</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Béraut</nom>
    <type>P</type>
    <ID>P1533</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Béreau, Pierre</nom>
    <type>P</type>
    <ID>P1534</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bergeron</nom>
    <type>P</type>
    <ID>P700</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bernabeau</nom>
    <type>P</type>
    <ID>P705</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bernage, Sieur de</nom>
    <type>P</type>
    <ID>P708</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bernard</nom>
    <type>P</type>
    <ID>P712</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Berne</nom>
    <type>P</type>
    <ID>P722</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Béroule, Sieur de</nom>
    <type>P</type>
    <ID>P1538</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Berteau, Pierre</nom>
    <type>P</type>
    <ID>P745</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Berthelot</nom>
    <type>P</type>
    <ID>P754</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Berthelot de Préneuf</nom>
    <type>P</type>
    <ID>P759</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bertin</nom>
    <type>P</type>
    <ID>P767</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Besons, M. de</nom>
    <type>P</type>
    <ID>P783</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Besson</nom>
    <type>P</type>
    <ID>P787</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Beurrey</nom>
    <type>P</type>
    <ID>P798</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bezart</nom>
    <type>P</type>
    <ID>P801</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bezons, Louis Bazin de</nom>
    <type>P</type>
    <ID>P804</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bidé de La Granville</nom>
    <type>P</type>
    <ID>P809</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bidé de Maurville</nom>
    <type>P</type>
    <ID>P810</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bignon</nom>
    <type>P</type>
    <ID>P814</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bigot</nom>
    <type>P</type>
    <ID>P817</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Billy, Sieur de</nom>
    <type>P</type>
    <ID>P841</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Binau, Demoiselle</nom>
    <type>P</type>
    <ID>P843</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Binaud</nom>
    <type>P</type>
    <ID>P844</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Binault</nom>
    <type>P</type>
    <ID>P847</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bions</nom>
    <type>P</type>
    <ID>P852</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bithomas</nom>
    <type>P</type>
    <ID>P867</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Blain</nom>
    <type>P</type>
    <ID>P873</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Blainville</nom>
    <type>P</type>
    <ID>P875</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Blanchard</nom>
    <type>P</type>
    <ID>P879</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Blatin</nom>
    <type>P</type>
    <ID>P894</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Blénac Roumegoux, Sieur de</nom>
    <type>P</type>
    <ID>P910</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Blénac, Sieur de</nom>
    <type>P</type>
    <ID>P913</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bleor, François Bitaud de</nom>
    <type>P</type>
    <ID>P897</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Blésac, de</nom>
    <type>P</type>
    <ID>P917</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bochard, de Sarron</nom>
    <type>P</type>
    <ID>P920</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bochet, Blaise</nom>
    <type>P</type>
    <ID>P921</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bœuf</nom>
    <type>P</type>
    <ID>P1546</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Boireau, Jacques</nom>
    <type>P</type>
    <ID>P933</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Boireau, Mathurin</nom>
    <type>P</type>
    <ID>P934</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Boisragon, Demoiselle de</nom>
    <type>P</type>
    <ID>P976</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Boisseau</nom>
    <type>P</type>
    <ID>P989</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Boissyraymé, de</nom>
    <type>P</type>
    <ID>P1003</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bonaud</nom>
    <type>P</type>
    <ID>P1019</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bonnaire, de</nom>
    <type>P</type>
    <ID>P1034</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bonnaventure, M. de</nom>
    <type>P</type>
    <ID>P1040</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bonneau, Dame</nom>
    <type>P</type>
    <ID>P1052</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bonnegens, Sieur de</nom>
    <type>P</type>
    <ID>P1056</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bonnemie, de</nom>
    <type>P</type>
    <ID>P1061</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bonnemort</nom>
    <type>P</type>
    <ID>P1064</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bonnet</nom>
    <type>P</type>
    <ID>P1066</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bonnichon, Julien</nom>
    <type>P</type>
    <ID>P1076</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bonrepaus, M. de</nom>
    <type>P</type>
    <ID>P1082</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bordères</nom>
    <type>P</type>
    <ID>P1106</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bordier</nom>
    <type>P</type>
    <ID>P1102</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Borie</nom>
    <type>P</type>
    <ID>P1108</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bostuste</nom>
    <type>P</type>
    <ID>P1121</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bouchet</nom>
    <type>P</type>
    <ID>P1132</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bouchu</nom>
    <type>P</type>
    <ID>P1139</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bouffard, Dame</nom>
    <type>P</type>
    <ID>P1148</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bouillet</nom>
    <type>P</type>
    <ID>P1157</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bouraud</nom>
    <type>P</type>
    <ID>P1179</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bourdet</nom>
    <type>P</type>
    <ID>P1182</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bouridal, de</nom>
    <type>P</type>
    <ID>P1212</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bourigaud</nom>
    <type>P</type>
    <ID>P1214</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bourlet</nom>
    <type>P</type>
    <ID>P1217</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bourry, de</nom>
    <type>P</type>
    <ID>P1222</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Boutein, Moyse</nom>
    <type>P</type>
    <ID>P1232</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Boutin, Guillame</nom>
    <type>P</type>
    <ID>P1241</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Boutineau</nom>
    <type>P</type>
    <ID>P1243</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Boutteville, dit La feuille</nom>
    <type>P</type>
    <ID>P1252</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Boutteville, M. de</nom>
    <type>P</type>
    <ID>P1251</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bouvier, Jean</nom>
    <type>P</type>
    <ID>P1255</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bouville, M. de</nom>
    <type>P</type>
    <ID>P1257</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Boyer</nom>
    <type>P</type>
    <ID>P1268</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Brach</nom>
    <type>P</type>
    <ID>P1277</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Brache, Sieur de</nom>
    <type>P</type>
    <ID>P1281</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Brandebourg, M. de</nom>
    <type>P</type>
    <ID>P1295</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Breard</nom>
    <type>P</type>
    <ID>P1310</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Breman (alias Brement), Michel</nom>
    <type>P</type>
    <ID>P1318</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bremant</nom>
    <type>P</type>
    <ID>P1321</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bressac, Madame de</nom>
    <type>P</type>
    <ID>P1328</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bretueil, M. de</nom>
    <type>P</type>
    <ID>P1341</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Breüil, Sieur de</nom>
    <type>P</type>
    <ID>P1345</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Breuilles, Sieur de</nom>
    <type>P</type>
    <ID>P1343</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bricard</nom>
    <type>P</type>
    <ID>P1354</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Brisacier</nom>
    <type>P</type>
    <ID>P1365</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Brochard</nom>
    <type>P</type>
    <ID>P1377</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Brodart</nom>
    <type>P</type>
    <ID>P1383</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Brossard des Broues</nom>
    <type>P</type>
    <ID>P1388</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Broteau, François</nom>
    <type>P</type>
    <ID>P1396</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Brousson</nom>
    <type>P</type>
    <ID>P1403</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Brun</nom>
    <type>P</type>
    <ID>P1414</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Brunel, Benoît</nom>
    <type>P</type>
    <ID>P1417</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Brunelière</nom>
    <type>P</type>
    <ID>P1418</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Brunier, Jean</nom>
    <type>P</type>
    <ID>P1427</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Buiret</nom>
    <type>P</type>
    <ID>P1458</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Buirette</nom>
    <type>P</type>
    <ID>P1459</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Buisson</nom>
    <type>P</type>
    <ID>P1461</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bureau</nom>
    <type>P</type>
    <ID>P1467</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Burgauld</nom>
    <type>P</type>
    <ID>P1473</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Burgues, Sieur de</nom>
    <type>P</type>
    <ID>P1474</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bury, Jacques</nom>
    <type>P</type>
    <ID>P1477</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Busnot, Marie</nom>
    <type>P</type>
    <ID>P1479</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Bussac, Demoiselles de</nom>
    <type>P</type>
    <ID>P1482</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>But</nom>
    <type>P</type>
    <ID>P1487</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Cabanac, Sieur de (alias Cabanat)</nom>
    <type>P</type>
    <ID>P1549</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Cabèce</nom>
    <type>P</type>
    <ID>P1558</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Caillau</nom>
    <type>P</type>
    <ID>P1573</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Caillières, de</nom>
    <type>P</type>
    <ID>P1580</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Candé</nom>
    <type>P</type>
    <ID>P1620</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Candezze</nom>
    <type>P</type>
    <ID>P1619</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Cannet</nom>
    <type>P</type>
    <ID>P1623</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Capiau</nom>
    <type>P</type>
    <ID>P1629</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Cardaillac, Le chevalier de</nom>
    <type>P</type>
    <ID>P1636</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Carré</nom>
    <type>P</type>
    <ID>P1661</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Cartereau (alias Cartreau)</nom>
    <type>P</type>
    <ID>P1663</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Cartigny, de</nom>
    <type>P</type>
    <ID>P1666</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Carton</nom>
    <type>P</type>
    <ID>P1668</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Carzon, François</nom>
    <type>P</type>
    <ID>P1672</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Cassel, Fleury du</nom>
    <type>P</type>
    <ID>P1677</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Castain (alias Castaing)</nom>
    <type>P</type>
    <ID>P1681</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Castaing, François</nom>
    <type>P</type>
    <ID>P1684</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Castigny, Sieur de (ou Cartigny)</nom>
    <type>P</type>
    <ID>P1690</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Catalan</nom>
    <type>P</type>
    <ID>P1696</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Caumartin, Louis-Urbain de</nom>
    <type>P</type>
    <ID>P1702</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Caumont</nom>
    <type>P</type>
    <ID>P1703</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Cazaus, de</nom>
    <type>P</type>
    <ID>P1727</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Cazeville</nom>
    <type>P</type>
    <ID>P1732</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Ceberet</nom>
    <type>P</type>
    <ID>P1733</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chaban, Sieur de</nom>
    <type>P</type>
    <ID>P1743</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chabert</nom>
    <type>P</type>
    <ID>P1751</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chabot</nom>
    <type>P</type>
    <ID>P1757</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chadefeau, Antoine</nom>
    <type>P</type>
    <ID>P1768</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chaigneau</nom>
    <type>P</type>
    <ID>P1773</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chaillaud</nom>
    <type>P</type>
    <ID>P1774</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chaillé</nom>
    <type>P</type>
    <ID>P1777</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chaintreau</nom>
    <type>P</type>
    <ID>P1780</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chaix</nom>
    <type>P</type>
    <ID>P1781</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chalais, Le chevalier de</nom>
    <type>P</type>
    <ID>P1783</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chalumeau, Veuve</nom>
    <type>P</type>
    <ID>P1791</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chamblé</nom>
    <type>P</type>
    <ID>P1797</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chambon, Galien de</nom>
    <type>P</type>
    <ID>P1798</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chamillart, Le chevalier de</nom>
    <type>P</type>
    <ID>P1804</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Champigny, de</nom>
    <type>P</type>
    <ID>P1824</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Champmeslin, de</nom>
    <type>P</type>
    <ID>P1833</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chanlatte</nom>
    <type>P</type>
    <ID>P1840</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chanvry, Antoine</nom>
    <type>P</type>
    <ID>P1849</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chapotot</nom>
    <type>P</type>
    <ID>P1864</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Charitte</nom>
    <type>P</type>
    <ID>P1881</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Charles</nom>
    <type>P</type>
    <ID>P1887</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Charonnier</nom>
    <type>P</type>
    <ID>P1913</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Charrier</nom>
    <type>P</type>
    <ID>P1920</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Charrières, de</nom>
    <type>P</type>
    <ID>P1925</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Charrin</nom>
    <type>P</type>
    <ID>P1924</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Charron de Salles, Le sieur de</nom>
    <type>P</type>
    <ID>P1927</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chasseloup, Demoiselle</nom>
    <type>P</type>
    <ID>P1935</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chasteauneuf</nom>
    <type>P</type>
    <ID>P1950</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chastelain, Dame</nom>
    <type>P</type>
    <ID>P1955</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chastillon, Sieur de</nom>
    <type>P</type>
    <ID>P1968</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chateaufort, Sieur de</nom>
    <type>P</type>
    <ID>P1975</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chateauguillaume, Sieur de</nom>
    <type>P</type>
    <ID>P1978</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chateaumorant, de</nom>
    <type>P</type>
    <ID>P1982</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>chateauneuf</nom>
    <type>P</type>
    <ID>P9819</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chateaurenault, François-Louis Rousselet</nom>
    <type>P</type>
    <ID>P1988</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chatellaillon, M. de</nom>
    <type>P</type>
    <ID>P1994</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chaulnes, M. de</nom>
    <type>P</type>
    <ID>P2004</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chaumel</nom>
    <type>P</type>
    <ID>P2005</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chauveau</nom>
    <type>P</type>
    <ID>P2011</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chauvet, François</nom>
    <type>P</type>
    <ID>P2024</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chavagnac, de</nom>
    <type>P</type>
    <ID>P2036</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chaviteau</nom>
    <type>P</type>
    <ID>P2044</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chaviteau, Jacques</nom>
    <type>P</type>
    <ID>P2046</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Cheise</nom>
    <type>P</type>
    <ID>P2053</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chenevois</nom>
    <type>P</type>
    <ID>P2057</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Cheroutel</nom>
    <type>P</type>
    <ID>P2062</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Cheury, Marquis de</nom>
    <type>P</type>
    <ID>P2069</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chevalier</nom>
    <type>P</type>
    <ID>P2073</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chevreuse, Duc de</nom>
    <type>P</type>
    <ID>P2097</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chevrières, sieur de</nom>
    <type>P</type>
    <ID>P2100</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chevry, Marquis de</nom>
    <type>P</type>
    <ID>P2101</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Chezant</nom>
    <type>P</type>
    <ID>P2105</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Ciré, Marquis de</nom>
    <type>P</type>
    <ID>P2161</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Clairambault</nom>
    <type>P</type>
    <ID>P2165</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Clairau</nom>
    <type>P</type>
    <ID>P2166</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Clairville</nom>
    <type>P</type>
    <ID>P2171</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Clancy, de</nom>
    <type>P</type>
    <ID>P2175</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Claverie</nom>
    <type>P</type>
    <ID>P2187</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Clérac, Sieur de</nom>
    <type>P</type>
    <ID>P2215</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Clercau</nom>
    <type>P</type>
    <ID>P2193</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Clereau</nom>
    <type>P</type>
    <ID>P2194</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Cloche, Le Père</nom>
    <type>P</type>
    <ID>P2209</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Coderk</nom>
    <type>P</type>
    <ID>P2225</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Coëtlogon, Le chevalier de</nom>
    <type>P</type>
    <ID>P2452</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Coigné</nom>
    <type>P</type>
    <ID>P2238</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Colardeau</nom>
    <type>P</type>
    <ID>P2241</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Colbert de Terron</nom>
    <type>P</type>
    <ID>P2245</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Colineau</nom>
    <type>P</type>
    <ID>P2250</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Combes, Sieur de</nom>
    <type>P</type>
    <ID>P2262</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Compagnon</nom>
    <type>P</type>
    <ID>P2270</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Comte</nom>
    <type>P</type>
    <ID>P2275</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <nom>Conteneuil, Sieur de</nom>
    <type>P</type>
    <ID>P2298</ID>
  </DATA_RECORD>
  <DATA_RECORD>