<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE master [
  <!ELEMENT master (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (unittitle?,function?,ID?)+>
  <!ELEMENT unittitle (#PCDATA)>
  <!ELEMENT function (#PCDATA)>
  <!ELEMENT ID (#PCDATA)>
]>
<master>
  <DATA_RECORD>
    <unittitle>Adrien, Veuve Timothée</unittitle>
    <function>Personne</function>
    <ID>P17</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Aigron, Demoiselle</unittitle>
    <function>Personne</function>
    <ID>P25</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Albert, Jean</unittitle>
    <function>Personne</function>
    <ID>P33</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Aldin, Jean (alias Alding)</unittitle>
    <function>Personne</function>
    <ID>P35</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Alizeau, François</unittitle>
    <function>Personne</function>
    <ID>P40</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Allain, Pierre</unittitle>
    <function>Personne</function>
    <ID>P44</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Allaire Dubeignon, Henry</unittitle>
    <function>Personne</function>
    <ID>P46</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Allaire, Louis</unittitle>
    <function>Personne</function>
    <ID>P49</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Allard</unittitle>
    <function>Personne</function>
    <ID>P51</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Alvarez</unittitle>
    <function>Personne</function>
    <ID>P67</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Amoreux</unittitle>
    <function>Personne</function>
    <ID>P84</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Anceau</unittitle>
    <function>Personne</function>
    <ID>P88</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>André</unittitle>
    <function>Personne</function>
    <ID>P93</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Aniaba, prince d'Assinie</unittitle>
    <function>Personne</function>
    <ID>P100</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Apoil</unittitle>
    <function>Personne</function>
    <ID>P108</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Ardouin</unittitle>
    <function>Personne</function>
    <ID>P120</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Argenton</unittitle>
    <function>Personne</function>
    <ID>P123</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Argoud</unittitle>
    <function>Personne</function>
    <ID>P126</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Arnaud</unittitle>
    <function>Personne</function>
    <ID>P130</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Arnaudin</unittitle>
    <function>Personne</function>
    <ID>P138</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Arnoul</unittitle>
    <function>Personne</function>
    <ID>P143</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Astier (alias Hastier)</unittitle>
    <function>Personne</function>
    <ID>P158</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Astruc</unittitle>
    <function>Personne</function>
    <ID>P160</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Aubouin</unittitle>
    <function>Personne</function>
    <ID>P176</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Aubry, Marie-Françoise</unittitle>
    <function>Personne</function>
    <ID>P180</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Audebert (alias Audibert) de la Morinière, Théophile</unittitle>
    <function>Personne</function>
    <ID>P183</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Audet</unittitle>
    <function>Personne</function>
    <ID>P184</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Audureau</unittitle>
    <function>Personne</function>
    <ID>P197</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Auger</unittitle>
    <function>Personne</function>
    <ID>P201</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Ausourd, Jean</unittitle>
    <function>Personne</function>
    <ID>P221</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Aynesy</unittitle>
    <function>Personne</function>
    <ID>P240</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Baatz, Charles de</unittitle>
    <function>Personne</function>
    <ID>P243</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Babin, Elie</unittitle>
    <function>Personne</function>
    <ID>P254</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bacher, Charles</unittitle>
    <function>Personne</function>
    <ID>P263</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bagneux, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P267</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Baguet</unittitle>
    <function>Personne</function>
    <ID>P269</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bailleul, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P274</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Balan</unittitle>
    <function>Personne</function>
    <ID>P281</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Balon</unittitle>
    <function>Personne</function>
    <ID>P291</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Banville, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P297</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Baptiste</unittitle>
    <function>Personne</function>
    <ID>P299</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Baragué</unittitle>
    <function>Personne</function>
    <ID>P301</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Barail (alias Barrail, Barrailh)</unittitle>
    <function>Personne</function>
    <ID>P302</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Barault (alias Bareau)</unittitle>
    <function>Personne</function>
    <ID>P316</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Barbaut, Jacques</unittitle>
    <function>Personne</function>
    <ID>P319</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Barbaut, Marianne</unittitle>
    <function>Personne</function>
    <ID>P320</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Barbeau</unittitle>
    <function>Personne</function>
    <ID>P325</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Barbeau des conches</unittitle>
    <function>Personne</function>
    <ID>P326</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Barber</unittitle>
    <function>Personne</function>
    <ID>P329</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Barbesieux, Louis-François-Marie Le Tellier</unittitle>
    <function>Personne</function>
    <ID>P331</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Barbot</unittitle>
    <function>Personne</function>
    <ID>P338</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Barcanon</unittitle>
    <function>Personne</function>
    <ID>P345</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bardet de Boisneau</unittitle>
    <function>Personne</function>
    <ID>P349</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bardet, Demoiselle</unittitle>
    <function>Personne</function>
    <ID>P351</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bardreau</unittitle>
    <function>Personne</function>
    <ID>P359</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Baroil</unittitle>
    <function>Personne</function>
    <ID>P372</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Baroire, le président de</unittitle>
    <function>Personne</function>
    <ID>P373</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Barreau</unittitle>
    <function>Personne</function>
    <ID>P388</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bart</unittitle>
    <function>Personne</function>
    <ID>P407</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bassemaison</unittitle>
    <function>Personne</function>
    <ID>P413</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Basset</unittitle>
    <function>Personne</function>
    <ID>P414</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bastet</unittitle>
    <function>Personne</function>
    <ID>P421</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Basville, Nicolas de Lamoignon</unittitle>
    <function>Personne</function>
    <ID>P425</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Baubriant (alias Baubriand)</unittitle>
    <function>Personne</function>
    <ID>P431</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bauché, Blaise</unittitle>
    <function>Personne</function>
    <ID>P434</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Baudin</unittitle>
    <function>Personne</function>
    <ID>P438</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Baudouin</unittitle>
    <function>Personne</function>
    <ID>P444</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Baudran</unittitle>
    <function>Personne</function>
    <ID>P449</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Baudré</unittitle>
    <function>Personne</function>
    <ID>P455</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Baugier, Edmé-Antoine</unittitle>
    <function>Personne</function>
    <ID>P459</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Baurie</unittitle>
    <function>Personne</function>
    <ID>P468</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Beat, Isaac</unittitle>
    <function>Personne</function>
    <ID>P477</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Beaubriand-Levêque, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P480</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Beauharnais, de</unittitle>
    <function>Personne</function>
    <ID>P508</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Beaujeu, Le chevalier de</unittitle>
    <function>Personne</function>
    <ID>P517</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Beaulieu</unittitle>
    <function>Personne</function>
    <ID>P521</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Beaumont, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P537</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Beauregard</unittitle>
    <function>Personne</function>
    <ID>P544</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Beaurepaire, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P551</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Beauvais, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P564</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Beccancourt, Le chevalier de</unittitle>
    <function>Personne</function>
    <ID>P577</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Béchet</unittitle>
    <function>Personne</function>
    <ID>P1498</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Béchet, les frères</unittitle>
    <function>Personne</function>
    <ID>P1501</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bégon, Michel</unittitle>
    <function>Personne</function>
    <ID>P1510</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Belcier</unittitle>
    <function>Personne</function>
    <ID>P595</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bellair, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P610</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Belle-Isle, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P614</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bellefonds</unittitle>
    <function>Personne</function>
    <ID>P618</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bellefonds, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P620</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bellinzani</unittitle>
    <function>Personne</function>
    <ID>P633</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bellisle Errard, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P637</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bellisle, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P640</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Belmont, de</unittitle>
    <function>Personne</function>
    <ID>P655</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Belon</unittitle>
    <function>Personne</function>
    <ID>P659</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Belot-Lamoureux</unittitle>
    <function>Personne</function>
    <ID>P665</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bennes, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P680</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Béraud</unittitle>
    <function>Personne</function>
    <ID>P1529</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Béraut</unittitle>
    <function>Personne</function>
    <ID>P1533</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Béreau, Pierre</unittitle>
    <function>Personne</function>
    <ID>P1534</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bergeron</unittitle>
    <function>Personne</function>
    <ID>P700</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bernabeau</unittitle>
    <function>Personne</function>
    <ID>P705</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bernage, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P708</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bernard</unittitle>
    <function>Personne</function>
    <ID>P712</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Berne</unittitle>
    <function>Personne</function>
    <ID>P722</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Béroule, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P1538</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Berteau, Pierre</unittitle>
    <function>Personne</function>
    <ID>P745</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Berthelot</unittitle>
    <function>Personne</function>
    <ID>P754</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Berthelot de Préneuf</unittitle>
    <function>Personne</function>
    <ID>P759</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bertin</unittitle>
    <function>Personne</function>
    <ID>P767</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Besons, M. de</unittitle>
    <function>Personne</function>
    <ID>P783</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Besson</unittitle>
    <function>Personne</function>
    <ID>P787</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Beurrey</unittitle>
    <function>Personne</function>
    <ID>P798</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bezart</unittitle>
    <function>Personne</function>
    <ID>P801</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bezons, Louis Bazin de</unittitle>
    <function>Personne</function>
    <ID>P804</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bidé de La Granville</unittitle>
    <function>Personne</function>
    <ID>P809</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bidé de Maurville</unittitle>
    <function>Personne</function>
    <ID>P810</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bignon</unittitle>
    <function>Personne</function>
    <ID>P814</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bigot</unittitle>
    <function>Personne</function>
    <ID>P817</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Billy, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P841</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Binau, Demoiselle</unittitle>
    <function>Personne</function>
    <ID>P843</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Binaud</unittitle>
    <function>Personne</function>
    <ID>P844</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Binault</unittitle>
    <function>Personne</function>
    <ID>P847</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bions</unittitle>
    <function>Personne</function>
    <ID>P852</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bithomas</unittitle>
    <function>Personne</function>
    <ID>P867</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Blain</unittitle>
    <function>Personne</function>
    <ID>P873</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Blainville</unittitle>
    <function>Personne</function>
    <ID>P875</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Blanchard</unittitle>
    <function>Personne</function>
    <ID>P879</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Blatin</unittitle>
    <function>Personne</function>
    <ID>P894</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Blénac Roumegoux, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P910</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Blénac, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P913</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bleor, François Bitaud de</unittitle>
    <function>Personne</function>
    <ID>P897</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Blésac, de</unittitle>
    <function>Personne</function>
    <ID>P917</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bochard, de Sarron</unittitle>
    <function>Personne</function>
    <ID>P920</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bochet, Blaise</unittitle>
    <function>Personne</function>
    <ID>P921</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bœuf</unittitle>
    <function>Personne</function>
    <ID>P1546</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Boireau, Jacques</unittitle>
    <function>Personne</function>
    <ID>P933</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Boireau, Mathurin</unittitle>
    <function>Personne</function>
    <ID>P934</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Boisragon, Demoiselle de</unittitle>
    <function>Personne</function>
    <ID>P976</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Boisseau</unittitle>
    <function>Personne</function>
    <ID>P989</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Boissyraymé, de</unittitle>
    <function>Personne</function>
    <ID>P1003</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bonaud</unittitle>
    <function>Personne</function>
    <ID>P1019</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bonnaire, de</unittitle>
    <function>Personne</function>
    <ID>P1034</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bonnaventure, M. de</unittitle>
    <function>Personne</function>
    <ID>P1040</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bonneau, Dame</unittitle>
    <function>Personne</function>
    <ID>P1052</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bonnegens, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P1056</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bonnemie, de</unittitle>
    <function>Personne</function>
    <ID>P1061</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bonnemort</unittitle>
    <function>Personne</function>
    <ID>P1064</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bonnet</unittitle>
    <function>Personne</function>
    <ID>P1066</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bonnichon, Julien</unittitle>
    <function>Personne</function>
    <ID>P1076</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bonrepaus, M. de</unittitle>
    <function>Personne</function>
    <ID>P1082</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bordères</unittitle>
    <function>Personne</function>
    <ID>P1106</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bordier</unittitle>
    <function>Personne</function>
    <ID>P1102</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Borie</unittitle>
    <function>Personne</function>
    <ID>P1108</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bostuste</unittitle>
    <function>Personne</function>
    <ID>P1121</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bouchet</unittitle>
    <function>Personne</function>
    <ID>P1132</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bouchu</unittitle>
    <function>Personne</function>
    <ID>P1139</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bouffard, Dame</unittitle>
    <function>Personne</function>
    <ID>P1148</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bouillet</unittitle>
    <function>Personne</function>
    <ID>P1157</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bouraud</unittitle>
    <function>Personne</function>
    <ID>P1179</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bourdet</unittitle>
    <function>Personne</function>
    <ID>P1182</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bouridal, de</unittitle>
    <function>Personne</function>
    <ID>P1212</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bourigaud</unittitle>
    <function>Personne</function>
    <ID>P1214</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bourlet</unittitle>
    <function>Personne</function>
    <ID>P1217</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bourry, de</unittitle>
    <function>Personne</function>
    <ID>P1222</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Boutein, Moyse</unittitle>
    <function>Personne</function>
    <ID>P1232</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Boutin, Guillame</unittitle>
    <function>Personne</function>
    <ID>P1241</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Boutineau</unittitle>
    <function>Personne</function>
    <ID>P1243</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Boutteville, dit La feuille</unittitle>
    <function>Personne</function>
    <ID>P1252</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Boutteville, M. de</unittitle>
    <function>Personne</function>
    <ID>P1251</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bouvier, Jean</unittitle>
    <function>Personne</function>
    <ID>P1255</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bouville, M. de</unittitle>
    <function>Personne</function>
    <ID>P1257</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Boyer</unittitle>
    <function>Personne</function>
    <ID>P1268</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Brach</unittitle>
    <function>Personne</function>
    <ID>P1277</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Brache, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P1281</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Brandebourg, M. de</unittitle>
    <function>Personne</function>
    <ID>P1295</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Breard</unittitle>
    <function>Personne</function>
    <ID>P1310</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Breman (alias Brement), Michel</unittitle>
    <function>Personne</function>
    <ID>P1318</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bremant</unittitle>
    <function>Personne</function>
    <ID>P1321</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bressac, Madame de</unittitle>
    <function>Personne</function>
    <ID>P1328</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bretueil, M. de</unittitle>
    <function>Personne</function>
    <ID>P1341</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Breüil, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P1345</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Breuilles, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P1343</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bricard</unittitle>
    <function>Personne</function>
    <ID>P1354</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Brisacier</unittitle>
    <function>Personne</function>
    <ID>P1365</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Brochard</unittitle>
    <function>Personne</function>
    <ID>P1377</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Brodart</unittitle>
    <function>Personne</function>
    <ID>P1383</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Brossard des Broues</unittitle>
    <function>Personne</function>
    <ID>P1388</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Broteau, François</unittitle>
    <function>Personne</function>
    <ID>P1396</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Brousson</unittitle>
    <function>Personne</function>
    <ID>P1403</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Brun</unittitle>
    <function>Personne</function>
    <ID>P1414</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Brunel, Benoît</unittitle>
    <function>Personne</function>
    <ID>P1417</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Brunelière</unittitle>
    <function>Personne</function>
    <ID>P1418</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Brunier, Jean</unittitle>
    <function>Personne</function>
    <ID>P1427</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Buiret</unittitle>
    <function>Personne</function>
    <ID>P1458</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Buirette</unittitle>
    <function>Personne</function>
    <ID>P1459</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Buisson</unittitle>
    <function>Personne</function>
    <ID>P1461</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bureau</unittitle>
    <function>Personne</function>
    <ID>P1467</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Burgauld</unittitle>
    <function>Personne</function>
    <ID>P1473</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Burgues, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P1474</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bury, Jacques</unittitle>
    <function>Personne</function>
    <ID>P1477</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Busnot, Marie</unittitle>
    <function>Personne</function>
    <ID>P1479</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Bussac, Demoiselles de</unittitle>
    <function>Personne</function>
    <ID>P1482</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>But</unittitle>
    <function>Personne</function>
    <ID>P1487</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Cabanac, Sieur de (alias Cabanat)</unittitle>
    <function>Personne</function>
    <ID>P1549</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Cabèce</unittitle>
    <function>Personne</function>
    <ID>P1558</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Caillau</unittitle>
    <function>Personne</function>
    <ID>P1573</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Caillières, de</unittitle>
    <function>Personne</function>
    <ID>P1580</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Candé</unittitle>
    <function>Personne</function>
    <ID>P1620</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Candezze</unittitle>
    <function>Personne</function>
    <ID>P1619</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Cannet</unittitle>
    <function>Personne</function>
    <ID>P1623</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Capiau</unittitle>
    <function>Personne</function>
    <ID>P1629</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Cardaillac, Le chevalier de</unittitle>
    <function>Personne</function>
    <ID>P1636</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Carré</unittitle>
    <function>Personne</function>
    <ID>P1661</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Cartereau (alias Cartreau)</unittitle>
    <function>Personne</function>
    <ID>P1663</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Cartigny, de</unittitle>
    <function>Personne</function>
    <ID>P1666</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Carton</unittitle>
    <function>Personne</function>
    <ID>P1668</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Carzon, François</unittitle>
    <function>Personne</function>
    <ID>P1672</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Cassel, Fleury du</unittitle>
    <function>Personne</function>
    <ID>P1677</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Castain (alias Castaing)</unittitle>
    <function>Personne</function>
    <ID>P1681</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Castaing, François</unittitle>
    <function>Personne</function>
    <ID>P1684</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Castigny, Sieur de (ou Cartigny)</unittitle>
    <function>Personne</function>
    <ID>P1690</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Catalan</unittitle>
    <function>Personne</function>
    <ID>P1696</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Caumartin, Louis-Urbain de</unittitle>
    <function>Personne</function>
    <ID>P1702</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Caumont</unittitle>
    <function>Personne</function>
    <ID>P1703</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Cazaus, de</unittitle>
    <function>Personne</function>
    <ID>P1727</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Cazeville</unittitle>
    <function>Personne</function>
    <ID>P1732</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Ceberet</unittitle>
    <function>Personne</function>
    <ID>P1733</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Chaban, Sieur de</unittitle>
    <function>Personne</function>
    <ID>P1743</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Chabert</unittitle>
    <function>Personne</function>
    <ID>P1751</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Chabot</unittitle>
    <function>Personne</function>
    <ID>P1757</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Chadefeau, Antoine</unittitle>
    <function>Personne</function>
    <ID>P1768</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Chaigneau</unittitle>
    <function>Personne</function>
    <ID>P1773</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Chaillaud</unittitle>
    <function>Personne</function>
    <ID>P1774</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Chaillé</unittitle>
    <function>Personne</function>
    <ID>P1777</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Chaintreau</unittitle>
    <function>Personne</function>
    <ID>P1780</ID>
  </DATA_RECORD>
  <DATA_RECORD>
    <unittitle>Chaix</unittitle>
    <function>Personne</function>
    <ID>P1781</ID>