<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tome7 [
  <!ELEMENT tome7 (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (function?,unittitle?,dateD?,dateF?,f1?,f2?,f3?,f4?,f5?,f6?,f7?,f8?,f9?,f10?,f11?,f12?,f13?,f14?,f15?,f16?,f17?,f18?,f19?,f20?,f21?,f22?,f23?,f24?,f25?,sserie?,serie?,ssserie?,atl?,mf?,ID?,cID?,aID?,contenu?,tome?,page?)+>
  <!ELEMENT function (#PCDATA)>
  <!ELEMENT unittitle (#PCDATA)>
  <!ELEMENT dateD (#PCDATA)>
  <!ELEMENT dateF (#PCDATA)>
  <!ELEMENT f1 (#PCDATA)>
  <!ELEMENT f2 (#PCDATA)>
  <!ELEMENT f3 (#PCDATA)>
  <!ELEMENT f4 (#PCDATA)>
  <!ELEMENT f5 (#PCDATA)>
  <!ELEMENT f6 (#PCDATA)>
  <!ELEMENT f7 (#PCDATA)>
  <!ELEMENT f8 (#PCDATA)>
  <!ELEMENT f9 (#PCDATA)>
  <!ELEMENT f10 (#PCDATA)>
  <!ELEMENT f11 (#PCDATA)>
  <!ELEMENT f12 (#PCDATA)>
  <!ELEMENT f13 (#PCDATA)>
  <!ELEMENT f14 (#PCDATA)>
  <!ELEMENT f15 (#PCDATA)>
  <!ELEMENT f16 (#PCDATA)>
  <!ELEMENT f17 (#PCDATA)>
  <!ELEMENT f18 (#PCDATA)>
  <!ELEMENT f19 (#PCDATA)>
  <!ELEMENT f20 (#PCDATA)>
  <!ELEMENT f21 (#PCDATA)>
  <!ELEMENT f22 (#PCDATA)>
  <!ELEMENT f23 (#PCDATA)>
  <!ELEMENT f24 (#PCDATA)>
  <!ELEMENT f25 (#PCDATA)>
  <!ELEMENT sserie (#PCDATA)>
  <!ELEMENT serie (#PCDATA)>
  <!ELEMENT ssserie (#PCDATA)>
  <!ELEMENT atl (#PCDATA)>
  <!ELEMENT mf (#PCDATA)>
  <!ELEMENT ID (#PCDATA)>
  <!ELEMENT cID (#PCDATA)>
  <!ELEMENT aID (#PCDATA)>
  <!ELEMENT contenu (#PCDATA)>
  <!ELEMENT tome (#PCDATA)>
  <!ELEMENT page (#PCDATA)>
]>
<tome7>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Acou</unittitle>
    <dateD>1727</dateD>
    <dateF>1727</dateF>
    <f1>385</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>110</atl>
    <mf>44</mf>
    <ID>P11</ID>
    <cID>C47</cID>
    <aID>MR1E110</aID>
    <contenu>Nègre condamné aux galères à perpétuité est en prison à Rochefort.</contenu>
    <tome>7</tome>
    <page>1</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Alquier</unittitle>
    <dateD>1727</dateD>
    <dateF>1727</dateF>
    <f1>233v</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>L</serie>
    <ssserie>1</ssserie>
    <atl>6</atl>
    <mf></mf>
    <ID>P65</ID>
    <cID>C358</cID>
    <aID>MR1L1.06</aID>
    <contenu>Ecrivain ordinaire, ordre de servir à Rochefort.</contenu>
    <tome>7</tome>
    <page>1</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amariton</unittitle>
    <dateD>1730</dateD>
    <dateF>1730</dateF>
    <f1>545</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>115</atl>
    <mf>47</mf>
    <ID>P72</ID>
    <cID>C378</cID>
    <aID>MR1E115</aID>
    <contenu>Passe au Canada sur la flûte le Dromadaire.</contenu>
    <tome>7</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1726</dateD>
    <dateF>1726</dateF>
    <f1>80</f1>
    <f2>489</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>107</atl>
    <mf>43</mf>
    <ID>P79</ID>
    <cID>C406</cID>
    <aID>MR1E107</aID>
    <contenu>Intendant de la généralité de la Rochelle.</contenu>
    <tome>7</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1726</dateD>
    <dateF>1726</dateF>
    <f1>80</f1>
    <f2>489</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>107</atl>
    <mf>43</mf>
    <ID>P79</ID>
    <cID>C406</cID>
    <aID>MR1E107</aID>
    <contenu>Intendant de la généralité de la Rochelle.</contenu>
    <tome>7</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1726</dateD>
    <dateF>1726</dateF>
    <f1>95</f1>
    <f2>640</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>108</atl>
    <mf>43</mf>
    <ID>P79</ID>
    <cID>C406</cID>
    <aID>MR1E108</aID>
    <contenu>Intendant de la généralité de la Rochelle.</contenu>
    <tome>7</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1726</dateD>
    <dateF>1726</dateF>
    <f1>95</f1>
    <f2>640</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>108</atl>
    <mf>43</mf>
    <ID>P79</ID>
    <cID>C406</cID>
    <aID>MR1E108</aID>
    <contenu>Intendant de la généralité de la Rochelle.</contenu>
    <tome>7</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1729</dateD>
    <dateF>1729</dateF>
    <f1>17</f1>
    <f2>49</f2>
    <f3>108</f3>
    <f4>139</f4>
    <f5>155</f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>A</serie>
    <ssserie></ssserie>
    <atl>9</atl>
    <mf></mf>
    <ID>P79</ID>
    <cID>C399</cID>
    <aID>MR1A9</aID>
    <contenu>Cantonnement des compagnies franches.</contenu>
    <tome>7</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Alquier</unittitle>
    <dateD>1727</dateD>
    <dateF>1727</dateF>
    <f1>235r</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>L</serie>
    <ssserie>1</ssserie>
    <atl>6</atl>
    <mf></mf>
    <ID>P65</ID>
    <cID>C357</cID>
    <aID>MR1L1.06</aID>
    <contenu>Brevet d’écrivain ordinaire de la Marine.</contenu>
    <tome>7</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Alquier de la Rambergue</unittitle>
    <dateD>1727</dateD>
    <dateF>1727</dateF>
    <f1>13</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>109</atl>
    <mf>44</mf>
    <ID>P66</ID>
    <cID>C360</cID>
    <aID>MR1E109</aID>
    <contenu>trésorier des invalides de la marine à St Valéry sur Somme à 350 livres par an.</contenu>
    <tome>7</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1727</dateD>
    <dateF>1727</dateF>
    <f1>541</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>109</atl>
    <mf>44</mf>
    <ID>P91</ID>
    <cID>C485</cID>
    <aID>MR1E109</aID>
    <contenu>Maître d’équipage a demandé un congé, refusé.</contenu>
    <tome>7</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1727</dateD>
    <dateF>1727</dateF>
    <f1>451</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>110</atl>
    <mf>44</mf>
    <ID>P91</ID>
    <cID>C467</cID>
    <aID>MR1E110</aID>
    <contenu>A fait des propositions pour relever la Garonne.</contenu>
    <tome>7</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1728</dateD>
    <dateF>1728</dateF>
    <f1>64</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>111</atl>
    <mf>45</mf>
    <ID>P91</ID>
    <cID>C468</cID>
    <aID>MR1E111</aID>
    <contenu>A fait des propositions pour relever la Garonne.</contenu>
    <tome>7</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1728</dateD>
    <dateF>1728</dateF>
    <f1>97</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>111</atl>
    <mf>45</mf>
    <ID>P91</ID>
    <cID>C483</cID>
    <aID>MR1E111</aID>
    <contenu>Le roi lui accorde un brevet de lieutenant de port à condition qu’il continue à remplir les fonctions de maître d’équipage. De plus il est surnuméraire à 1500 livres par an en attendant une place vacante.</contenu>
    <tome>7</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1728</dateD>
    <dateF>1728</dateF>
    <f1>138</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>111</atl>
    <mf>45</mf>
    <ID>P91</ID>
    <cID>C481</cID>
    <aID>MR1E111</aID>
    <contenu>Le ministre demande qu’on lui envoi un petit modèle en bois de l’appareil qu’Andrieu veut employer pour déséchouer la Garonne.</contenu>
    <tome>7</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1728</dateD>
    <dateF>1728</dateF>
    <f1>144</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>111</atl>
    <mf>45</mf>
    <ID>P91</ID>
    <cID>C491</cID>
    <aID>MR1E111</aID>
    <contenu>Reçoit son brevet de lieutenant de port.</contenu>
    <tome>7</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1728</dateD>
    <dateF>1728</dateF>
    <f1>163</f1>
    <f2>229</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>111</atl>
    <mf>45</mf>
    <ID>P91</ID>
    <cID>C469</cID>
    <aID>MR1E111</aID>
    <contenu>A écrit au ministre qu’il a deux fils qui ont de bonnes dispositions pour le service de la marine.</contenu>
    <tome>7</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1728</dateD>
    <dateF>1728</dateF>
    <f1>289</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>111</atl>
    <mf>45</mf>
    <ID>P91</ID>
    <cID>C492</cID>
    <aID>MR1E111</aID>
    <contenu>Son fils aîné devra faire quelques campagnes sur mer avant qu’on l’entretienne dans le port. Le plus jeune sera admis comme élève.</contenu>
    <tome>7</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1728</dateD>
    <dateF>1728</dateF>
    <f1>387</f1>
    <f2>414</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>111</atl>
    <mf>45</mf>
    <ID>P91</ID>
    <cID>C493</cID>
    <aID>MR1E111</aID>
    <contenu>Son fils aîné restera au port pour travailler avec son père.</contenu>
    <tome>7</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Ancelin</unittitle>
    <dateD>1727</dateD>
    <dateF>1727</dateF>
    <f1>153</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>109</atl>
    <mf>44</mf>
    <ID>P89</ID>
    <cID>C464</cID>
    <aID>MR1E109</aID>
    <contenu>Dame son passage avec trois enfants lui est accordé sur un navire marchand de la Rochelle. Elle va rejoindre son mari à la Martinique.</contenu>
    <tome>7</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amman</unittitle>
    <dateD>1727</dateD>
    <dateF>1727</dateF>
    <f1>75</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>109</atl>
    <mf>44</mf>
    <ID>P83</ID>
    <cID>C427</cID>
    <aID>MR1E109</aID>
    <contenu>Officier du régiment suisse de Karrer.</contenu>
    <tome>7</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amman</unittitle>
    <dateD>1728</dateD>
    <dateF>1728</dateF>
    <f1>341</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>112</atl>
    <mf>45</mf>
    <ID>P83</ID>
    <cID>C426</cID>
    <aID>MR1E112</aID>
    <contenu>En garnison à la Martinique.</contenu>
    <tome>7</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1728</dateD>
    <dateF>1728</dateF>
    <f1>146</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>112</atl>
    <mf>45</mf>
    <ID>P91</ID>
    <cID>C486</cID>
    <aID>MR1E112</aID>
    <contenu>Maître d’équipage, gratification de 600£ accordée au père pour l’entretien et l’éducation de son fils employé à l’arsenal.</contenu>
    <tome>7</tome>
    <page>4</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1729</dateD>
    <dateF>1729</dateF>
    <f1>445</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>113</atl>
    <mf>46</mf>
    <ID>P91</ID>
    <cID>C482</cID>
    <aID>MR1E113</aID>
    <contenu>Le ministre veut bien lui continuer sa gratification de 600£ pour l’aider à l’éducation de son fils, celui-ci sera nommé sous maître d’équipage quand il aura navigué.</contenu>
    <tome>7</tome>
    <page>4</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1730</dateD>
    <dateF>1730</dateF>
    <f1>109</f1>
    <f2>150</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>115</atl>
    <mf>47</mf>
    <ID>P91</ID>
    <cID>C488</cID>
    <aID>MR1E115</aID>
    <contenu>Nommé écrivain à 480 livres par an.</contenu>
    <tome>7</tome>
    <page>4</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1730</dateD>
    <dateF>1730</dateF>
    <f1>37r</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>L</serie>
    <ssserie>1</ssserie>
    <atl>6</atl>
    <mf></mf>
    <ID>P91</ID>
    <cID>C470</cID>
    <aID>MR1L1.06</aID>
    <contenu>Brevet de lieutenant de port.</contenu>
    <tome>7</tome>
    <page>4</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1730</dateD>
    <dateF>1730</dateF>
    <f1>149v</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>L</serie>
    <ssserie>1</ssserie>
    <atl>6</atl>
    <mf></mf>
    <ID>P91</ID>
    <cID>C489</cID>
    <aID>MR1L1.06</aID>
    <contenu>Ordre de servir au port de Rochefort.</contenu>
    <tome>7</tome>
    <page>4</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1730</dateD>
    <dateF>1730</dateF>
    <f1>161v</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>L</serie>
    <ssserie>1</ssserie>
    <atl>6</atl>
    <mf></mf>
    <ID>P91</ID>
    <cID>C471</cID>
    <aID>MR1L1.06</aID>
    <contenu>Brevet d’écrivain ordinaire de la marine.</contenu>
    <tome>7</tome>
    <page>4</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Angerant</unittitle>
    <dateD>1726</dateD>
    <dateF>1726</dateF>
    <f1>639</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>108</atl>
    <mf>43</mf>
    <ID>P98</ID>
    <cID>C513</cID>
    <aID>MR1E108</aID>
    <contenu>Ecrivain sa solde est porté à 60 livres par mois.</contenu>
    <tome>7</tome>
    <page>4</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Ange</unittitle>
    <dateD>1728</dateD>
    <dateF>1728</dateF>
    <f1>355</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>111</atl>
    <mf>45</mf>
    <ID>P97</ID>
    <cID>C510</cID>
    <aID>MR1E111</aID>
    <contenu>Hospitalier de l’hôpital général de Villemain à Montréal .</contenu>
    <tome>7</tome>
    <page>4</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Ange</unittitle>
    <dateD>1729</dateD>
    <dateF>1729</dateF>
    <f1>301</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>113</atl>
    <mf>46</mf>
    <ID>P97</ID>
    <cID>C511</cID>
    <aID>MR1E113</aID>
    <contenu>Sera passager sur l'Eléphant.</contenu>
    <tome>7</tome>
    <page>4</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Bachelot</unittitle>
    <dateD>1727</dateD>
    <dateF>1727</dateF>
    <f1>254v</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>L</serie>
    <ssserie>1</ssserie>
    <atl>6</atl>
    <mf></mf>
    <ID>P262</ID>
    <cID>C2075</cID>
    <aID>MR1L1.06</aID>
    <contenu>Ecrivain ordinaire du département de Toulon, ordre de passer à Rochefort.</contenu>
    <tome>7</tome>
    <page>5</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Ardibus</unittitle>
    <dateD>1727</dateD>
    <dateF>1727</dateF>
    <f1>368</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>110</atl>
    <mf>44</mf>
    <ID>P117</ID>
    <cID>C585</cID>
    <aID>MR1E110</aID>
    <contenu>Père, écrivain, sa solde est portée à 720£ par an.</contenu>
    <tome>7</tome>
    <page>5</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Ardibus</unittitle>
    <dateD>1728</dateD>
    <dateF>1728</dateF>
    <f1>243</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>112</atl>
    <mf>45</mf>
    <ID>P117</ID>
    <cID>C586</cID>
    <aID>MR1E112</aID>
    <contenu>Reçoit une gratification de 150£.</contenu>
    <tome>7</tome>
    <page>5</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Ardibus</unittitle>
    <dateD>1730</dateD>
    <dateF>1730</dateF>
    <f1>111</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>