<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tome1 [
  <!ELEMENT tome1 (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (function?,unittitle?,dateD?,dateF?,f1?,f2?,f3?,f4?,f5?,f6?,f7?,f8?,f9?,f10?,f11?,f12?,f13?,f14?,f15?,f16?,f17?,f18?,f19?,f20?,f21?,f22?,f23?,f24?,f25?,sserie?,serie?,ssserie?,atl?,mf?,ID?,cID?,aID?,contenu?,tome?,page?)+>
  <!ELEMENT function (#PCDATA)>
  <!ELEMENT unittitle (#PCDATA)>
  <!ELEMENT dateD (#PCDATA)>
  <!ELEMENT dateF (#PCDATA)>
  <!ELEMENT f1 (#PCDATA)>
  <!ELEMENT f2 (#PCDATA)>
  <!ELEMENT f3 (#PCDATA)>
  <!ELEMENT f4 (#PCDATA)>
  <!ELEMENT f5 (#PCDATA)>
  <!ELEMENT f6 (#PCDATA)>
  <!ELEMENT f7 (#PCDATA)>
  <!ELEMENT f8 (#PCDATA)>
  <!ELEMENT f9 (#PCDATA)>
  <!ELEMENT f10 (#PCDATA)>
  <!ELEMENT f11 (#PCDATA)>
  <!ELEMENT f12 (#PCDATA)>
  <!ELEMENT f13 (#PCDATA)>
  <!ELEMENT f14 (#PCDATA)>
  <!ELEMENT f15 (#PCDATA)>
  <!ELEMENT f16 (#PCDATA)>
  <!ELEMENT f17 (#PCDATA)>
  <!ELEMENT f18 (#PCDATA)>
  <!ELEMENT f19 (#PCDATA)>
  <!ELEMENT f20 (#PCDATA)>
  <!ELEMENT f21 (#PCDATA)>
  <!ELEMENT f22 (#PCDATA)>
  <!ELEMENT f23 (#PCDATA)>
  <!ELEMENT f24 (#PCDATA)>
  <!ELEMENT f25 (#PCDATA)>
  <!ELEMENT sserie (#PCDATA)>
  <!ELEMENT serie (#PCDATA)>
  <!ELEMENT ssserie (#PCDATA)>
  <!ELEMENT atl (#PCDATA)>
  <!ELEMENT mf (#PCDATA)>
  <!ELEMENT ID (#PCDATA)>
  <!ELEMENT cID (#PCDATA)>
  <!ELEMENT aID (#PCDATA)>
  <!ELEMENT contenu (#PCDATA)>
  <!ELEMENT tome (#PCDATA)>
  <!ELEMENT page (#PCDATA)>
]>
<tome1>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Allaire, Louis</unittitle>
    <dateD>1673</dateD>
    <dateF>1673</dateF>
    <f1>271</f1>
    <f2>276</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>32</atl>
    <mf>1</mf>
    <ID>P49</ID>
    <cID>C326</cID>
    <aID>MR1E32</aID>
    <contenu>Marchand de La Rochelle. Lui payer 3000 livres.</contenu>
    <tome>1</tome>
    <page>88</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Aigron, Demoiselle</unittitle>
    <dateD>1689</dateD>
    <dateF>1689</dateF>
    <f1>299</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>33</atl>
    <mf>2</mf>
    <ID>P25</ID>
    <cID>C163</cID>
    <aID>MR1E33</aID>
    <contenu>Se plaint de sa famille qui l'a prise en haine, à cause de sa conversion.</contenu>
    <tome>1</tome>
    <page>88</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Aldin, Jean (alias Alding)</unittitle>
    <dateD>1694</dateD>
    <dateF>1694</dateF>
    <f1>435</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>36</atl>
    <mf>3</mf>
    <ID>P35</ID>
    <cID>C274</cID>
    <aID>MR1E36</aID>
    <contenu>Prisonnier anglais au château d'Angoulême, mis en liberté sous caution. </contenu>
    <tome>1</tome>
    <page>88</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Aldin, Jean (alias Alding)</unittitle>
    <dateD>1694</dateD>
    <dateF>1694</dateF>
    <f1>532</f1>
    <f2>641</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>36</atl>
    <mf>3</mf>
    <ID>P35</ID>
    <cID>C273</cID>
    <aID>MR1E36</aID>
    <contenu>A des conférences avec des habitants de La Rochelle. Le transférer au château Trompette.</contenu>
    <tome>1</tome>
    <page>88</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Albert, Jean</unittitle>
    <dateD>1696</dateD>
    <dateF>1696</dateF>
    <f1>135</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>37</atl>
    <mf>3</mf>
    <ID>P33</ID>
    <cID>C237</cID>
    <aID>MR1E37</aID>
    <contenu>Collecteur de la paroisse de Passirat, en 1695.</contenu>
    <tome>1</tome>
    <page>88</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Adrien, Veuve Timothée</unittitle>
    <dateD>1697</dateD>
    <dateF>1697</dateF>
    <f1>420</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>40</atl>
    <mf>5</mf>
    <ID>P17</ID>
    <cID>C54</cID>
    <aID>MR1E40</aID>
    <contenu>Ses filles mises au couvent.</contenu>
    <tome>1</tome>
    <page>88</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Alizeau, François</unittitle>
    <dateD>1700</dateD>
    <dateF>1700</dateF>
    <f1>311</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>42</atl>
    <mf>6</mf>
    <ID>P40</ID>
    <cID>C282</cID>
    <aID>MR1E42</aID>
    <contenu>De l'île de Ré.</contenu>
    <tome>1</tome>
    <page>88</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Allain, Pierre</unittitle>
    <dateD>1700</dateD>
    <dateF>1700</dateF>
    <f1>307</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>42</atl>
    <mf>6</mf>
    <ID>P44</ID>
    <cID>C291</cID>
    <aID>MR1E42</aID>
    <contenu>Maître couvreur à l'île de Ré.</contenu>
    <tome>1</tome>
    <page>88</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Argenton</unittitle>
    <dateD>1672</dateD>
    <dateF>1672</dateF>
    <f1>0</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>32</atl>
    <mf>1</mf>
    <ID>P123</ID>
    <cID>C602</cID>
    <aID>MR1E32</aID>
    <contenu>Ecrivain de la corderie.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Anceau</unittitle>
    <dateD>1689</dateD>
    <dateF>1689</dateF>
    <f1>72</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>33</atl>
    <mf>2</mf>
    <ID>P88</ID>
    <cID>C457</cID>
    <aID>MR1E33</aID>
    <contenu>Fournisseur de mâts.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Anceau</unittitle>
    <dateD>1690</dateD>
    <dateF>1690</dateF>
    <f1>76</f1>
    <f2>98</f2>
    <f3>115</f3>
    <f4>138</f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>34</atl>
    <mf>2</mf>
    <ID>P88</ID>
    <cID>C458</cID>
    <aID>MR1E34</aID>
    <contenu>L'obliger à augmenter sa fourniture de mâts.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Anceau</unittitle>
    <dateD>1691</dateD>
    <dateF>1691</dateF>
    <f1>47</f1>
    <f2>175</f2>
    <f3>517</f3>
    <f4>609</f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>35</atl>
    <mf>2</mf>
    <ID>P88</ID>
    <cID>C459</cID>
    <aID>MR1E35</aID>
    <contenu>L'obliger à augmenter sa fourniture de mâts.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Alvarez</unittitle>
    <dateD>1691</dateD>
    <dateF>1691</dateF>
    <f1>21</f1>
    <f2>50</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>35</atl>
    <mf>2</mf>
    <ID>P67</ID>
    <cID>N190</cID>
    <aID>MR1E35</aID>
    <contenu></contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Allaire Dubeignon, Henry</unittitle>
    <dateD>1696</dateD>
    <dateF>1696</dateF>
    <f1>3</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>38</atl>
    <mf>4</mf>
    <ID>P46</ID>
    <cID>C300</cID>
    <aID>MR1E38</aID>
    <contenu>Juge de l'amirauté de La Rochelle. Ecrit au ministre au sujet de la vente de la cargaison du navire le Grand Alexandre pris par la Salamandre.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Allaire Dubeignon, Henry</unittitle>
    <dateD>1697</dateD>
    <dateF>1697</dateF>
    <f1>45</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>39</atl>
    <mf>5</mf>
    <ID>P46</ID>
    <cID>C301</cID>
    <aID>MR1E39</aID>
    <contenu>N'a pas eu connaissance de l'évasion de sa femme.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Allaire Dubeignon, Henry</unittitle>
    <dateD>1700</dateD>
    <dateF>1700</dateF>
    <f1>305</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>42</atl>
    <mf>6</mf>
    <ID>P46</ID>
    <cID>C302</cID>
    <aID>MR1E42</aID>
    <contenu>Syndic des pères capucins de La Rochelle.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>André</unittitle>
    <dateD>1696</dateD>
    <dateF>1696</dateF>
    <f1>57</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>38</atl>
    <mf>4</mf>
    <ID>P93</ID>
    <cID>C503</cID>
    <aID>MR1E38</aID>
    <contenu>Colon de l'Acadie.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Apoil</unittitle>
    <dateD>1696</dateD>
    <dateF>1696</dateF>
    <f1>171</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>38</atl>
    <mf>4</mf>
    <ID>P108</ID>
    <cID>N301</cID>
    <aID>MR1E38</aID>
    <contenu></contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Ardouin</unittitle>
    <dateD>1696</dateD>
    <dateF>1696</dateF>
    <f1>219</f1>
    <f2>221</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>37</atl>
    <mf>3</mf>
    <ID>P120</ID>
    <cID>C595</cID>
    <aID>MR1E37</aID>
    <contenu>Procureur à Saintes. Dénoncé comme protestant par le sieur Burgauld.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Ardouin</unittitle>
    <dateD>1696</dateD>
    <dateF>1696</dateF>
    <f1>679</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>37</atl>
    <mf>3</mf>
    <ID>P120</ID>
    <cID>C594</cID>
    <aID>MR1E37</aID>
    <contenu>Directeur des francs-fiefs à Saintes.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Argoud</unittitle>
    <dateD>1696</dateD>
    <dateF>1696</dateF>
    <f1>34</f1>
    <f2>151</f2>
    <f3>323</f3>
    <f4>444</f4>
    <f5>716</f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>38</atl>
    <mf>4</mf>
    <ID>P126</ID>
    <cID>C629</cID>
    <aID>MR1E38</aID>
    <contenu>Commissaire ordinaire de la Marine. Demande des boulets pour Bayonne.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Argoud</unittitle>
    <dateD>1697</dateD>
    <dateF>1697</dateF>
    <f1>300</f1>
    <f2>333</f2>
    <f3>437</f3>
    <f4>454</f4>
    <f5>469</f5>
    <f6>491</f6>
    <f7>664</f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>39</atl>
    <mf>5</mf>
    <ID>P126</ID>
    <cID>C630</cID>
    <aID>MR1E39</aID>
    <contenu>Commissaire ordinaire de la Marine. Demande des boulets pour Bayonne.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Argoud</unittitle>
    <dateD>1697</dateD>
    <dateF>1697</dateF>
    <f1>300</f1>
    <f2>333</f2>
    <f3>437</f3>
    <f4>454</f4>
    <f5>469</f5>
    <f6>491</f6>
    <f7>664</f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>39</atl>
    <mf>5</mf>
    <ID>P126</ID>
    <cID>C630</cID>
    <aID>MR1E39</aID>
    <contenu>Commissaire ordinaire de la Marine. Demande des boulets pour Bayonne.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Argoud</unittitle>
    <dateD>1697</dateD>
    <dateF>1697</dateF>
    <f1>163</f1>
    <f2>168</f2>
    <f3>205</f3>
    <f4>425</f4>
    <f5>526</f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>40</atl>
    <mf>5</mf>
    <ID>P126</ID>
    <cID>C630</cID>
    <aID>MR1E40</aID>
    <contenu>Commissaire ordinaire de la Marine. Demande des boulets pour Bayonne.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Argoud</unittitle>
    <dateD>1697</dateD>
    <dateF>1697</dateF>
    <f1>163</f1>
    <f2>168</f2>
    <f3>205</f3>
    <f4>425</f4>
    <f5>526</f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>40</atl>
    <mf>5</mf>
    <ID>P126</ID>
    <cID>C630</cID>
    <aID>MR1E40</aID>
    <contenu>Commissaire ordinaire de la Marine. Demande des boulets pour Bayonne.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Argoud</unittitle>
    <dateD>1700</dateD>
    <dateF>1700</dateF>
    <f1>751</f1>
    <f2>759</f2>
    <f3>794</f3>
    <f4>797</f4>
    <f5>825</f5>
    <f6>827</f6>
    <f7>846</f7>
    <f8>889</f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>43</atl>
    <mf>6</mf>
    <ID>P126</ID>
    <cID>C631</cID>
    <aID>MR1E43</aID>
    <contenu>Commissaire ordinaire de la Marine. Demande des boulets pour Bayonne.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amoreux</unittitle>
    <dateD>1697</dateD>
    <dateF>1697</dateF>
    <f1>460</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>39</atl>
    <mf>5</mf>
    <ID>P84</ID>
    <cID>C429</cID>
    <aID>MR1E39</aID>
    <contenu>Embarquera sur la Gloutonne pour aller aux îles y remplir la fonction de juge.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Arnaud</unittitle>
    <dateD>1697</dateD>
    <dateF>1697</dateF>
    <f1>281</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>39</atl>
    <mf>5</mf>
    <ID>P130</ID>
    <cID>N390</cID>
    <aID>MR1E39</aID>
    <contenu></contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Arnaud</unittitle>
    <dateD>1700</dateD>
    <dateF>1700</dateF>
    <f1>101</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>43</atl>
    <mf>6</mf>
    <ID>P130</ID>
    <cID>C666</cID>
    <aID>MR1E43</aID>
    <contenu>Charpentier.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Arnaud</unittitle>
    <dateD>1700</dateD>
    <dateF>1700</dateF>
    <f1>644</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>43</atl>
    <mf>6</mf>
    <ID>P130</ID>
    <cID>C665</cID>
    <aID>MR1E43</aID>
    <contenu>Capitaine de Royan. A levé une carte de la rivière de Bordeaux, elle est fausse, la détruire.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Allard</unittitle>
    <dateD>1700</dateD>
    <dateF>1700</dateF>
    <f1>144</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>43</atl>
    <mf>6</mf>
    <ID>P51</ID>
    <cID>N166</cID>
    <aID>MR1E43</aID>
    <contenu></contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Aniaba, prince d'Assinie</unittitle>
    <dateD>1700</dateD>
    <dateF>1700</dateF>
    <f1>805</f1>
    <f2>857</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>43</atl>
    <mf>6</mf>
    <ID>P100</ID>
    <cID>C521</cID>
    <aID>MR1E43</aID>
    <contenu>Sera rapatrié par le vaisseau le Poli.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Aniaba, prince d'Assinie</unittitle>
    <dateD>1700</dateD>
    <dateF>1700</dateF>
    <f1>895</f1>
    <f2>928</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>43</atl>
    <mf>6</mf>
    <ID>P100</ID>
    <cID>C520</cID>
    <aID>MR1E43</aID>
    <contenu>A besoin de quelques ustensiles pour son voyage, les acheter à bon marché.</contenu>
    <tome>1</tome>
    <page>89</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Arnoul</unittitle>
    <dateD>1672</dateD>
    <dateF>1672</dateF>
    <f1>22</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>32</atl>
    <mf>1</mf>
    <ID>P143</ID>
    <cID>C697</cID>
    <aID>MR1E32</aID>
    <contenu>Doit venir à Rochefort.</contenu>
    <tome>1</tome>
    <page>90</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Arnoul</unittitle>
    <dateD>1690</dateD>
    <dateF>1690</dateF>
    <f1>136</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>34</atl>
    <mf>2</mf>
    <ID>P143</ID>
    <cID>C695</cID>
    <aID>MR1E34</aID>
    <contenu>A fait un voyage aux Pyrénées pour surveiller la fourniture des mâts.</contenu>
    <tome>1</tome>
    <page>90</page>
  </DATA_RECORD>
  <DATA_RECORD>