<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tome8 [
  <!ELEMENT tome8 (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (function?,unittitle?,dateD?,dateF?,f1?,f2?,f3?,f4?,f5?,f6?,f7?,f8?,f9?,f10?,f11?,f12?,f13?,f14?,f15?,f16?,f17?,f18?,f19?,f20?,f21?,f22?,f23?,f24?,f25?,sserie?,serie?,ssserie?,atl?,mf?,ID?,cID?,aID?,contenu?,tome?,page?)+>
  <!ELEMENT function (#PCDATA)>
  <!ELEMENT unittitle (#PCDATA)>
  <!ELEMENT dateD (#PCDATA)>
  <!ELEMENT dateF (#PCDATA)>
  <!ELEMENT f1 (#PCDATA)>
  <!ELEMENT f2 (#PCDATA)>
  <!ELEMENT f3 (#PCDATA)>
  <!ELEMENT f4 (#PCDATA)>
  <!ELEMENT f5 (#PCDATA)>
  <!ELEMENT f6 (#PCDATA)>
  <!ELEMENT f7 (#PCDATA)>
  <!ELEMENT f8 (#PCDATA)>
  <!ELEMENT f9 (#PCDATA)>
  <!ELEMENT f10 (#PCDATA)>
  <!ELEMENT f11 (#PCDATA)>
  <!ELEMENT f12 (#PCDATA)>
  <!ELEMENT f13 (#PCDATA)>
  <!ELEMENT f14 (#PCDATA)>
  <!ELEMENT f15 (#PCDATA)>
  <!ELEMENT f16 (#PCDATA)>
  <!ELEMENT f17 (#PCDATA)>
  <!ELEMENT f18 (#PCDATA)>
  <!ELEMENT f19 (#PCDATA)>
  <!ELEMENT f20 (#PCDATA)>
  <!ELEMENT f21 (#PCDATA)>
  <!ELEMENT f22 (#PCDATA)>
  <!ELEMENT f23 (#PCDATA)>
  <!ELEMENT f24 (#PCDATA)>
  <!ELEMENT f25 (#PCDATA)>
  <!ELEMENT sserie (#PCDATA)>
  <!ELEMENT serie (#PCDATA)>
  <!ELEMENT ssserie (#PCDATA)>
  <!ELEMENT atl (#PCDATA)>
  <!ELEMENT mf (#PCDATA)>
  <!ELEMENT ID (#PCDATA)>
  <!ELEMENT cID (#PCDATA)>
  <!ELEMENT aID (#PCDATA)>
  <!ELEMENT contenu (#PCDATA)>
  <!ELEMENT tome (#PCDATA)>
  <!ELEMENT page (#PCDATA)>
]>
<tome8>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Allard-Belin</unittitle>
    <dateD>1735</dateD>
    <dateF>1735</dateF>
    <f1>222</f1>
    <f2>271</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>123</atl>
    <mf>51</mf>
    <ID>P54</ID>
    <cID>C343</cID>
    <aID>MR1E123</aID>
    <contenu>Offre le prêt à 90 livres le tonneau ce qui est une pistole au-dessous des offres du Sieur Rasteau le Ministre est disposé à accepter.</contenu>
    <tome>8</tome>
    <page>1</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Allard-Belin</unittitle>
    <dateD>1735</dateD>
    <dateF>1735</dateF>
    <f1>275</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>123</atl>
    <mf>51</mf>
    <ID>P54</ID>
    <cID>C340</cID>
    <aID>MR1E123</aID>
    <contenu>L’intendant Beauharnais a traité avec lui pour le prêt de Saint-Domingue à 85 livres le tonneau.</contenu>
    <tome>8</tome>
    <page>1</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Allard-Belin</unittitle>
    <dateD>1735</dateD>
    <dateF>1735</dateF>
    <f1>305</f1>
    <f2>407</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>123</atl>
    <mf>51</mf>
    <ID>P54</ID>
    <cID>C344</cID>
    <aID>MR1E123</aID>
    <contenu>Son navire la Généreuse portera les effets à Saint-Domingue.</contenu>
    <tome>8</tome>
    <page>1</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1732</dateD>
    <dateF>1732</dateF>
    <f1>121</f1>
    <f2>254</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>116</atl>
    <mf>48</mf>
    <ID>P91</ID>
    <cID>C474</cID>
    <aID>MR1E116</aID>
    <contenu>Droits de fermes sur les bois.</contenu>
    <tome>8</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1732</dateD>
    <dateF>1732</dateF>
    <f1>121</f1>
    <f2>254</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>116</atl>
    <mf>48</mf>
    <ID>P91</ID>
    <cID>C474</cID>
    <aID>MR1E116</aID>
    <contenu>Droits de fermes sur les bois.</contenu>
    <tome>8</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1732</dateD>
    <dateF>1732</dateF>
    <f1>128</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>117</atl>
    <mf>48</mf>
    <ID>P91</ID>
    <cID>C474</cID>
    <aID>MR1E117</aID>
    <contenu>Droits de fermes sur les bois.</contenu>
    <tome>8</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1732</dateD>
    <dateF>1732</dateF>
    <f1>128</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>117</atl>
    <mf>48</mf>
    <ID>P91</ID>
    <cID>C474</cID>
    <aID>MR1E117</aID>
    <contenu>Droits de fermes sur les bois.</contenu>
    <tome>8</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1732</dateD>
    <dateF>1732</dateF>
    <f1>295</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>117</atl>
    <mf>48</mf>
    <ID>P91</ID>
    <cID>C473</cID>
    <aID>MR1E117</aID>
    <contenu>Demande au ministre d’accorder l’entretien à son fils pour l’instruction duquel il a reçu 600 livres par an.</contenu>
    <tome>8</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1732</dateD>
    <dateF>1732</dateF>
    <f1>421</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>117</atl>
    <mf>48</mf>
    <ID>P91</ID>
    <cID>C478</cID>
    <aID>MR1E117</aID>
    <contenu>Le Ministre le trouve trop jeune pour lui accorder un brevet de 1er maître d’équipage, mais il veut bien le faire entretenir comme maître d’équipage sur le pied de 600 livres.</contenu>
    <tome>8</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1733</dateD>
    <dateF>1733</dateF>
    <f1>229</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>118</atl>
    <mf>49</mf>
    <ID>P91</ID>
    <cID>C479</cID>
    <aID>MR1E118</aID>
    <contenu>Le Ministre le trouve trop jeune pour lui accorder un brevet de 1er maître d’équipage, mais il veut bien le faire entretenir comme maître d’équipage sur le pied de 600 livres.</contenu>
    <tome>8</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1734</dateD>
    <dateF>1734</dateF>
    <f1>271</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>121</atl>
    <mf>50</mf>
    <ID>P91</ID>
    <cID>C490</cID>
    <aID>MR1E121</aID>
    <contenu>Proposé pour remplir les fonctions de maître d’équipage.</contenu>
    <tome>8</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1734</dateD>
    <dateF>1734</dateF>
    <f1>341</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>121</atl>
    <mf>50</mf>
    <ID>P91</ID>
    <cID>C476</cID>
    <aID>MR1E121</aID>
    <contenu>Fait des difficultés pour occuper le poste et cela en vue d’accélérer l’avancement de son fils. Le Ministre est disposé à nommer le fils Andrieu, enseigne de vaisseau et maître d’équipage à condition que son père le dirige et réponde de sa gestion, comme maître de manœuvre.</contenu>
    <tome>8</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1734</dateD>
    <dateF>1734</dateF>
    <f1>423</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>121</atl>
    <mf>50</mf>
    <ID>P91</ID>
    <cID>C480</cID>
    <aID>MR1E121</aID>
    <contenu>Le fils Andrieu est nommé aux appointements de 600 livres.</contenu>
    <tome>8</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Alquier</unittitle>
    <dateD>1735</dateD>
    <dateF>1735</dateF>
    <f1>209</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>122</atl>
    <mf>51</mf>
    <ID>P65</ID>
    <cID>C359</cID>
    <aID>MR1E122</aID>
    <contenu>Sa solde est portée à 720 livres.</contenu>
    <tome>8</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amman</unittitle>
    <dateD>1732</dateD>
    <dateF>1732</dateF>
    <f1>303</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>117</atl>
    <mf>48</mf>
    <ID>P83</ID>
    <cID>C425</cID>
    <aID>MR1E117</aID>
    <contenu>Capitaine, lieutenant de régiment suisse de Karrer à la Martinique.</contenu>
    <tome>8</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Arnaud</unittitle>
    <dateD>1732</dateD>
    <dateF>1732</dateF>
    <f1>109</f1>
    <f2>158</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>116</atl>
    <mf>48</mf>
    <ID>P130</ID>
    <cID>C672</cID>
    <aID>MR1E116</aID>
    <contenu>Maître de forges de Cosne, traité passe avec lui pour la fourniture d’ancres pour les éprouver, on les élève avec une grue et on les laisse tomber sur des canons de fer. C’est un moyen violent qui casse l’ancre et par lequel on ne voit que le grain de fer, trouver un autre procédé d’éprouver.</contenu>
    <tome>8</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Arnaud</unittitle>
    <dateD>1732</dateD>
    <dateF>1732</dateF>
    <f1>479</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>117</atl>
    <mf>48</mf>
    <ID>P130</ID>
    <cID>C663</cID>
    <aID>MR1E117</aID>
    <contenu>A envoyé à Rochefort une ancre de 3300 livres, l’éprouver.</contenu>
    <tome>8</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Arnaud</unittitle>
    <dateD>1733</dateD>
    <dateF>1733</dateF>
    <f1>132</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>118</atl>
    <mf>49</mf>
    <ID>P130</ID>
    <cID>C676</cID>
    <aID>MR1E118</aID>
    <contenu>a chargé le Sieur Racine de s’occuper de ses affaires de bois au Canada.</contenu>
    <tome>8</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Arnaud</unittitle>
    <dateD>1735</dateD>
    <dateF>1735</dateF>
    <f1>313</f1>
    <f2>413</f2>
    <f3>414</f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>122</atl>
    <mf>51</mf>
    <ID>P130</ID>
    <cID>C673</cID>
    <aID>MR1E122</aID>
    <contenu>Recevoir ces deux ancres, nonobstant le dommage qu’elles ont reçu par une trop forte épreuve, paiement.</contenu>
    <tome>8</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Artur</unittitle>
    <dateD>1735</dateD>
    <dateF>1735</dateF>
    <f1>437</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>123</atl>
    <mf>51</mf>
    <ID>P151</ID>
    <cID>C1693</cID>
    <aID>MR1E123</aID>
    <contenu>Le Ministre lui a procuré un livret de médecin du Roi, à Cayenne, sera passager sur la flûte la Charente.</contenu>
    <tome>8</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Ardibus</unittitle>
    <dateD>1733</dateD>
    <dateF>1733</dateF>
    <f1>181</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>119</atl>
    <mf>49</mf>
    <ID>P117</ID>
    <cID>C584</cID>
    <aID>MR1E119</aID>
    <contenu>Père, nommé écrivain principal servira au magasin général.</contenu>
    <tome>8</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Angerant</unittitle>
    <dateD>1734</dateD>
    <dateF>1734</dateF>
    <f1>347</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>121</atl>
    <mf>50</mf>
    <ID>P98</ID>
    <cID>C512</cID>
    <aID>MR1E121</aID>
    <contenu>Chargé de l’exploitation des bois de Champagne. Feras façonner des pièces propres pour les portes des formes de l’arsenal de Rochefort.</contenu>
    <tome>8</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Aubert, Louis</unittitle>
    <dateD>1733</dateD>
    <dateF>1733</dateF>
    <f1>239</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>118</atl>
    <mf>49</mf>
    <ID>P169</ID>
    <cID>C1808</cID>
    <aID>MR1E118</aID>
    <contenu>Dit la Liberté a servi dans les troupes de Canada et a obtenu un congé absolu, veut se rengager pour cette colonie, l’accepter.</contenu>
    <tome>8</tome>
    <page>4</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Aubert</unittitle>
    <dateD>1733</dateD>
    <dateF>1733</dateF>
    <f1>305</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>119</atl>
    <mf>49</mf>
    <ID>P163</ID>
    <cID>C1800</cID>
    <aID>MR1E119</aID>
    <contenu>Nommé greffier de la juridiction de Cayenne, sera passager de la flûte la Charente.</contenu>
    <tome>8</tome>
    <page>4</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Babaud</unittitle>
    <dateD>1732</dateD>
    <dateF>1732</dateF>
    <f1>11</f1>
    <f2>11</f2>
    <f3>25</f3>
    <f4>47</f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>116</atl>
    <mf>48</mf>
    <ID>P244</ID>
    <cID>C2031</cID>
    <aID>MR1E116</aID>
    <contenu>Fourniture de ménains.</contenu>
    <tome>8</tome>
    <page>4</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Babaud</unittitle>
    <dateD>1732</dateD>
    <dateF>1732</dateF>
    <f1>11</f1>
    <f2>11</f2>
    <f3>25</f3>
    <f4>47</f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>116</atl>
    <mf>48</mf>
    <ID>P244</ID>
    <cID>C2031</cID>
    <aID>MR1E116</aID>
    <contenu>Fourniture de ménains.</contenu>
    <tome>8</tome>
    <page>4</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Babaud</unittitle>
    <dateD>1732</dateD>
    <dateF>1732</dateF>
    <f1>212</f1>
    <f2>393</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>117</atl>
    <mf>48</mf>
    <ID>P244</ID>
    <cID>C2031</cID>
    <aID>MR1E117</aID>
    <contenu>Fourniture de ménains.</contenu>
    <tome>8</tome>
    <page>4</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Babaud</unittitle>
    <dateD>1732</dateD>
    <dateF>1732</dateF>
    <f1>212</f1>
    <f2>393</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>117</atl>
    <mf>48</mf>
    <ID>P244</ID>
    <cID>C2031</cID>
    <aID>MR1E117</aID>
    <contenu>Fourniture de ménains.</contenu>
    <tome>8</tome>
    <page>4</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Babaud</unittitle>
    <dateD>1734</dateD>
    <dateF>1734</dateF>
    <f1>258</f1>
    <f2>331</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>120</atl>
    <mf>50</mf>
    <ID>P244</ID>
    <cID>C2043</cID>
    <aID>MR1E1</aID>
    <contenu>Offre de fournir des bois d’Alsace et de Lorraine.</contenu>
    <tome>8</tome>
    <page>4</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Babaud</unittitle>
    <dateD>1734</dateD>
    <dateF>1734</dateF>
    <f1>195</f1>
    <f2>235</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>121</atl>
    <mf>50</mf>
    <ID>P244</ID>
    <cID>C2032</cID>
    <aID>MR1E121</aID>
    <contenu>Fourniture de ménains.</contenu>
    <tome>8</tome>
    <page>4</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Babaud</unittitle>
    <dateD>1735</dateD>
    <dateF>1735</dateF>
    <f1>319</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>123</atl>
    <mf>51</mf>
    <ID>P244</ID>
    <cID>C2033</cID>
    <aID>MR1E123</aID>
    <contenu>Fourniture de ménains.</contenu>
    <tome>8</tome>
    <page>4</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Auvinet</unittitle>
    <dateD>1734</dateD>
    <dateF>1734</dateF>
    <f1>113</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>120</atl>
    <mf>50</mf>
    <ID>P228</ID>
    <cID>C1999</cID>
    <aID>MR1E1</aID>
    <contenu>Maître calfat, mise des scellés chez lui après la mort de sa femme.</contenu>
    <tome>8</tome>
    <page>4</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Baptiste</unittitle>
    <dateD>1732</dateD>
    <dateF>1732</dateF>
    <f1>204</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>117</atl>
    <mf>48</mf>
    <ID>P299</ID>
    <cID>C2201</cID>
    <aID>MR1E117</aID>
    <contenu>Sauvage sioux amené en France par Monsieur Le Forant. Le Ministre l’avait fait venir à Paris et le renvoi à Rochefort pour embarquer sur la flûte la Gironde à destination de la Louisiane.</contenu>
    <tome>8</tome>
    <page>5</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Baptiste</unittitle>
    <dateD>1732</dateD>
    <dateF>1732</dateF>
    <f1>373</f1>
    <f2>524</f2>
    <f3>575</f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>