<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tome9 [
  <!ELEMENT tome9 (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (function?,unittitle?,dateD?,dateF?,f1?,f2?,f3?,f4?,f5?,f6?,f7?,f8?,f9?,f10?,f11?,f12?,f13?,f14?,f15?,f16?,f17?,f18?,f19?,f20?,f21?,f22?,f23?,f24?,f25?,sserie?,serie?,ssserie?,atl?,mf?,ID?,cID?,aID?,contenu?,tome?,page?)+>
  <!ELEMENT function (#PCDATA)>
  <!ELEMENT unittitle (#PCDATA)>
  <!ELEMENT dateD (#PCDATA)>
  <!ELEMENT dateF (#PCDATA)>
  <!ELEMENT f1 (#PCDATA)>
  <!ELEMENT f2 (#PCDATA)>
  <!ELEMENT f3 (#PCDATA)>
  <!ELEMENT f4 (#PCDATA)>
  <!ELEMENT f5 (#PCDATA)>
  <!ELEMENT f6 (#PCDATA)>
  <!ELEMENT f7 (#PCDATA)>
  <!ELEMENT f8 (#PCDATA)>
  <!ELEMENT f9 (#PCDATA)>
  <!ELEMENT f10 (#PCDATA)>
  <!ELEMENT f11 (#PCDATA)>
  <!ELEMENT f12 (#PCDATA)>
  <!ELEMENT f13 (#PCDATA)>
  <!ELEMENT f14 (#PCDATA)>
  <!ELEMENT f15 (#PCDATA)>
  <!ELEMENT f16 (#PCDATA)>
  <!ELEMENT f17 (#PCDATA)>
  <!ELEMENT f18 (#PCDATA)>
  <!ELEMENT f19 (#PCDATA)>
  <!ELEMENT f20 (#PCDATA)>
  <!ELEMENT f21 (#PCDATA)>
  <!ELEMENT f22 (#PCDATA)>
  <!ELEMENT f23 (#PCDATA)>
  <!ELEMENT f24 (#PCDATA)>
  <!ELEMENT f25 (#PCDATA)>
  <!ELEMENT sserie (#PCDATA)>
  <!ELEMENT serie (#PCDATA)>
  <!ELEMENT ssserie (#PCDATA)>
  <!ELEMENT atl (#PCDATA)>
  <!ELEMENT mf (#PCDATA)>
  <!ELEMENT ID (#PCDATA)>
  <!ELEMENT cID (#PCDATA)>
  <!ELEMENT aID (#PCDATA)>
  <!ELEMENT contenu (#PCDATA)>
  <!ELEMENT tome (#PCDATA)>
  <!ELEMENT page (#PCDATA)>
]>
<tome9>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Allard</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>299</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>124</atl>
    <mf>52</mf>
    <ID>P51</ID>
    <cID>C331</cID>
    <aID>MR1E124</aID>
    <contenu>Maitre tonnelier à La Rochelle, certificat.</contenu>
    <tome>9</tome>
    <page>1</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Almain</unittitle>
    <dateD>1739</dateD>
    <dateF>1739</dateF>
    <f1>359</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>129</atl>
    <mf>55</mf>
    <ID>P64</ID>
    <cID>C354</cID>
    <aID>MR1E129</aID>
    <contenu>Reçu élève.</contenu>
    <tome>9</tome>
    <page>1</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Allard-Belin</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>324</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>125</atl>
    <mf>52</mf>
    <ID>P54</ID>
    <cID>C342</cID>
    <aID>MR1E125</aID>
    <contenu>Négociant à La Rochelle. A offert au Ministre la frégate la Généreuse, pour porter des farines et des munitions.</contenu>
    <tome>9</tome>
    <page>1</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Allard-Belin</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>395</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>125</atl>
    <mf>52</mf>
    <ID>P54</ID>
    <cID>C338</cID>
    <aID>MR1E125</aID>
    <contenu>L'intendant a passé, avec lui, un traité pour porter à la Louisiane des troupes et des munitions.</contenu>
    <tome>9</tome>
    <page>1</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Allard-Belin</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>397</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>125</atl>
    <mf>52</mf>
    <ID>P54</ID>
    <cID>C339</cID>
    <aID>MR1E125</aID>
    <contenu>Le Ministre annule ce traité trop onéreux.</contenu>
    <tome>9</tome>
    <page>1</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>André, Pierre</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>229</f1>
    <f2>467</f2>
    <f3>479</f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>125</atl>
    <mf>52</mf>
    <ID>P94</ID>
    <cID>C507</cID>
    <aID>MR1E125</aID>
    <contenu>Sergent dans les troupes de la Louisiane. Sera passager sur la Somme.</contenu>
    <tome>9</tome>
    <page>1</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>André, Pierre</unittitle>
    <dateD>1737</dateD>
    <dateF>1737</dateF>
    <f1>293</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>126</atl>
    <mf>53</mf>
    <ID>P94</ID>
    <cID>C506</cID>
    <aID>MR1E126</aID>
    <contenu>Doit 100 livres au sergent Guichard.</contenu>
    <tome>9</tome>
    <page>1</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Alexis</unittitle>
    <dateD>1737</dateD>
    <dateF>1737</dateF>
    <f1>444</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>126</atl>
    <mf>53</mf>
    <ID>P39</ID>
    <cID>C279</cID>
    <aID>MR1E126</aID>
    <contenu>Frère de la Charité de Paris. Est destiné pour être chirurgien de l'hôpital de Louisbourg. Sera passager sur le Héros.</contenu>
    <tome>9</tome>
    <page>1</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Alléaume, Alexis</unittitle>
    <dateD>1737</dateD>
    <dateF>1737</dateF>
    <f1>323</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>126</atl>
    <mf>53</mf>
    <ID>P63</ID>
    <cID>C352</cID>
    <aID>MR1E126</aID>
    <contenu>Cordier. Demande la place de maitre-cordier à Québec. M Horquart décidera la chose.</contenu>
    <tome>9</tome>
    <page>1</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Ambois, François</unittitle>
    <dateD>1739</dateD>
    <dateF>1739</dateF>
    <f1>449</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>130</atl>
    <mf>55</mf>
    <ID>P75</ID>
    <cID>C396</cID>
    <aID>MR1E1</aID>
    <contenu>Dit sieur Martin. Soldat de la compagnie d'Habert proposé par la demi-solde.</contenu>
    <tome>9</tome>
    <page>1</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Ambois, François</unittitle>
    <dateD>1739</dateD>
    <dateF>1739</dateF>
    <f1>569</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>130</atl>
    <mf>55</mf>
    <ID>P75</ID>
    <cID>C395</cID>
    <aID>MR1E1</aID>
    <contenu>Admis à 6 livres par mois.</contenu>
    <tome>9</tome>
    <page>1</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Arnaud</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>349</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>125</atl>
    <mf>52</mf>
    <ID>P130</ID>
    <cID>C669</cID>
    <aID>MR1E125</aID>
    <contenu>Fournisseur d'ancres.</contenu>
    <tome>9</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Arnaud</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>404</f1>
    <f2>487</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>125</atl>
    <mf>52</mf>
    <ID>P130</ID>
    <cID>C670</cID>
    <aID>MR1E125</aID>
    <contenu>Les ancres bien forgées et bien proportionnées sont acceptées sans épreuve.</contenu>
    <tome>9</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Artur</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>254</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>125</atl>
    <mf>52</mf>
    <ID>P151</ID>
    <cID>C1697</cID>
    <aID>MR1E125</aID>
    <contenu>Médecin à Cayenne. A envoyé des plantes pour le jardin Royal.</contenu>
    <tome>9</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Artur</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>525</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>125</atl>
    <mf>52</mf>
    <ID>P151</ID>
    <cID>C1694</cID>
    <aID>MR1E125</aID>
    <contenu>Lui accorder un demi-tonneau de fût sur la flûte la Charente pour envoi de livres, etc.</contenu>
    <tome>9</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>81</f1>
    <f2>114</f2>
    <f3>153</f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>124</atl>
    <mf>52</mf>
    <ID>P91</ID>
    <cID>C477</cID>
    <aID>MR1E124</aID>
    <contenu>Fils. Fait les fonctions d'Enseigne de port.</contenu>
    <tome>9</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>503</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>125</atl>
    <mf>52</mf>
    <ID>P91</ID>
    <cID>C475</cID>
    <aID>MR1E125</aID>
    <contenu>Ecrivain. Sa solde est portée à 600 livres.</contenu>
    <tome>9</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Andrieu</unittitle>
    <dateD>1737</dateD>
    <dateF>1737</dateF>
    <f1>377</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>127</atl>
    <mf>53</mf>
    <ID>P91</ID>
    <cID>C487</cID>
    <aID>MR1E127</aID>
    <contenu>Nommé enseigne de port.</contenu>
    <tome>9</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Aubert</unittitle>
    <dateD>1738</dateD>
    <dateF>1738</dateF>
    <f1>855</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>128</atl>
    <mf>54</mf>
    <ID>P163</ID>
    <cID>C1795</cID>
    <aID>MR1E128</aID>
    <contenu>Chirurgien à la Louisiane. Le ministre lui a envoyé le brevet de Chirurgien major.</contenu>
    <tome>9</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Ardibus</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>85</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>124</atl>
    <mf>52</mf>
    <ID>P117</ID>
    <cID>C582</cID>
    <aID>MR1E124</aID>
    <contenu>Fils. Ecrivain. Sera passager sur l'Orox, pour la Martinique.</contenu>
    <tome>9</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Ardibus</unittitle>
    <dateD>1740</dateD>
    <dateF>1740</dateF>
    <f1>175</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>131</atl>
    <mf>56</mf>
    <ID>P117</ID>
    <cID>C589</cID>
    <aID>MR1E131</aID>
    <contenu>« Bon sujet ». Le Ministre convertit en gratification ordinaire la gratification extraordinaire de 200 livres.</contenu>
    <tome>9</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Armand, Jacques</unittitle>
    <dateD>1737</dateD>
    <dateF>1737</dateF>
    <f1>335</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>126</atl>
    <mf>53</mf>
    <ID>P129</ID>
    <cID>C659</cID>
    <aID>MR1E126</aID>
    <contenu>Maitre potier d'étain. Sera passager sur le Jason, pour retourner à Québec.</contenu>
    <tome>9</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Aubin</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>161</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>124</atl>
    <mf>52</mf>
    <ID>P171</ID>
    <cID>C1812</cID>
    <aID>MR1E124</aID>
    <contenu>Marchand de Tours. Fournisseur de bois de construction. Réclamation au sujet de bois refusés.</contenu>
    <tome>9</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Aubin</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>161</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>124</atl>
    <mf>52</mf>
    <ID>P171</ID>
    <cID>C1812</cID>
    <aID>MR1E124</aID>
    <contenu>Marchand de Tours. Fournisseur de bois de construction. Réclamation au sujet de bois refusés.</contenu>
    <tome>9</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Aubin</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>444</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>125</atl>
    <mf>52</mf>
    <ID>P171</ID>
    <cID>C1812</cID>
    <aID>MR1E125</aID>
    <contenu>Marchand de Tours. Fournisseur de bois de construction. Réclamation au sujet de bois refusés.</contenu>
    <tome>9</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Aubin</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>444</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>125</atl>
    <mf>52</mf>
    <ID>P171</ID>
    <cID>C1812</cID>
    <aID>MR1E125</aID>
    <contenu>Marchand de Tours. Fournisseur de bois de construction. Réclamation au sujet de bois refusés.</contenu>
    <tome>9</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Aubin</unittitle>
    <dateD>1738</dateD>
    <dateF>1738</dateF>
    <f1>137</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>128</atl>
    <mf>54</mf>
    <ID>P171</ID>
    <cID>C1813</cID>
    <aID>MR1E128</aID>
    <contenu>Marchand de Tours. Fournisseur de bois de construction. Réclamation au sujet de bois refusés.</contenu>
    <tome>9</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Aubin</unittitle>
    <dateD>1739</dateD>
    <dateF>1739</dateF>
    <f1>146</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>129</atl>
    <mf>55</mf>
    <ID>P171</ID>
    <cID>C1811</cID>
    <aID>MR1E129</aID>
    <contenu>Fait des difficultés pour rembourser les avances qui lui ont été faites pour son exploitation des bois.</contenu>
    <tome>9</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Aurain</unittitle>
    <dateD>1740</dateD>
    <dateF>1740</dateF>
    <f1>176</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>131</atl>
    <mf>56</mf>
    <ID>P213</ID>
    <cID>C1934</cID>
    <aID>MR1E131</aID>
    <contenu>Ecrivain. Sa solde est élevée à 720 livres.</contenu>
    <tome>9</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Auroy</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>503</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>125</atl>
    <mf>52</mf>
    <ID>P215</ID>
    <cID>C1982</cID>
    <aID>MR1E125</aID>
    <contenu>Pilote vice-amiral. Retraité avec 35 livres par mois. Remplira la place de maitre d'hydrographie, à Marennes.</contenu>
    <tome>9</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Auroy</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>503</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>125</atl>
    <mf>52</mf>
    <ID>P215</ID>
    <cID>C1979</cID>
    <aID>MR1E125</aID>
    <contenu>Décédé.</contenu>
    <tome>9</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Auroy</unittitle>
    <dateD>1737</dateD>
    <dateF>1737</dateF>
    <f1>79</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>126</atl>
    <mf>53</mf>
    <ID>P215</ID>
    <cID>C1983</cID>
    <aID>MR1E126</aID>
    <contenu>Pilote vice-amiral. Retraité avec 35 livres par mois. Remplira la place de maitre d'hydrographie, à Marennes.</contenu>
    <tome>9</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Auger, Paul</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>91</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>125</atl>
    <mf>52</mf>
    <ID>P206</ID>
    <cID>C1860</cID>
    <aID>MR1E125</aID>
    <contenu>Maître de Chatte. Gratification de 120 livres. Blessé en service.</contenu>
    <tome>9</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Audinet, Jean</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>299</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>125</atl>
    <mf>52</mf>
    <ID>P192</ID>
    <cID>C1842</cID>
    <aID>MR1E125</aID>
    <contenu>De La Rochelle. Fait un envoi à M. Des Rozes, à Cayenne.</contenu>
    <tome>9</tome>
    <page>3</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Auvray, Jacques</unittitle>
    <dateD>1736</dateD>
    <dateF>1736</dateF>
    <f1>231</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>