<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tome6 [
  <!ELEMENT tome6 (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (function?,unittitle?,dateD?,dateF?,f1?,f2?,f3?,f4?,f5?,f6?,f7?,f8?,f9?,f10?,f11?,f12?,f13?,f14?,f15?,f16?,f17?,f18?,f19?,f20?,f21?,f22?,f23?,f24?,f25?,sserie?,serie?,ssserie?,atl?,mf?,ID?,cID?,aID?,contenu?,tome?,page?)+>
  <!ELEMENT function (#PCDATA)>
  <!ELEMENT unittitle (#PCDATA)>
  <!ELEMENT dateD (#PCDATA)>
  <!ELEMENT dateF (#PCDATA)>
  <!ELEMENT f1 (#PCDATA)>
  <!ELEMENT f2 (#PCDATA)>
  <!ELEMENT f3 (#PCDATA)>
  <!ELEMENT f4 (#PCDATA)>
  <!ELEMENT f5 (#PCDATA)>
  <!ELEMENT f6 (#PCDATA)>
  <!ELEMENT f7 (#PCDATA)>
  <!ELEMENT f8 (#PCDATA)>
  <!ELEMENT f9 (#PCDATA)>
  <!ELEMENT f10 (#PCDATA)>
  <!ELEMENT f11 (#PCDATA)>
  <!ELEMENT f12 (#PCDATA)>
  <!ELEMENT f13 (#PCDATA)>
  <!ELEMENT f14 (#PCDATA)>
  <!ELEMENT f15 (#PCDATA)>
  <!ELEMENT f16 (#PCDATA)>
  <!ELEMENT f17 (#PCDATA)>
  <!ELEMENT f18 (#PCDATA)>
  <!ELEMENT f19 (#PCDATA)>
  <!ELEMENT f20 (#PCDATA)>
  <!ELEMENT f21 (#PCDATA)>
  <!ELEMENT f22 (#PCDATA)>
  <!ELEMENT f23 (#PCDATA)>
  <!ELEMENT f24 (#PCDATA)>
  <!ELEMENT f25 (#PCDATA)>
  <!ELEMENT sserie (#PCDATA)>
  <!ELEMENT serie (#PCDATA)>
  <!ELEMENT ssserie (#PCDATA)>
  <!ELEMENT atl (#PCDATA)>
  <!ELEMENT mf (#PCDATA)>
  <!ELEMENT ID (#PCDATA)>
  <!ELEMENT cID (#PCDATA)>
  <!ELEMENT aID (#PCDATA)>
  <!ELEMENT contenu (#PCDATA)>
  <!ELEMENT tome (#PCDATA)>
  <!ELEMENT page (#PCDATA)>
]>
<tome6>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Abraham</unittitle>
    <dateD>1722</dateD>
    <dateF>1722</dateF>
    <f1>229</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>100</atl>
    <mf>39</mf>
    <ID>P3</ID>
    <cID>N2</cID>
    <aID>MR1E0</aID>
    <contenu></contenu>
    <tome>6</tome>
    <page>1</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amariton</unittitle>
    <dateD>1722</dateD>
    <dateF>1722</dateF>
    <f1>729</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>99</atl>
    <mf>39</mf>
    <ID>P72</ID>
    <cID>C375</cID>
    <aID>MR1E99</aID>
    <contenu>Le Conseil lui a accordé le passage de deux engagés sur la flûte Le Chameau.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1721</dateD>
    <dateF>1721</dateF>
    <f1>14</f1>
    <f2>539</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>96</atl>
    <mf>37</mf>
    <ID>P79</ID>
    <cID>C403</cID>
    <aID>MR1E96</aID>
    <contenu>Intendant de La Rochelle.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1721</dateD>
    <dateF>1721</dateF>
    <f1>14</f1>
    <f2>539</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>96</atl>
    <mf>37</mf>
    <ID>P79</ID>
    <cID>C403</cID>
    <aID>MR1E96</aID>
    <contenu>Intendant de La Rochelle.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1721</dateD>
    <dateF>1721</dateF>
    <f1>340</f1>
    <f2>449</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>97</atl>
    <mf>37</mf>
    <ID>P79</ID>
    <cID>C403</cID>
    <aID>MR1E97</aID>
    <contenu>Intendant de La Rochelle.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1721</dateD>
    <dateF>1721</dateF>
    <f1>340</f1>
    <f2>449</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>97</atl>
    <mf>37</mf>
    <ID>P79</ID>
    <cID>C403</cID>
    <aID>MR1E97</aID>
    <contenu>Intendant de La Rochelle.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1722</dateD>
    <dateF>1722</dateF>
    <f1>751</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>99</atl>
    <mf>39</mf>
    <ID>P79</ID>
    <cID>C404</cID>
    <aID>MR1E99</aID>
    <contenu>Intendant de La Rochelle.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1722</dateD>
    <dateF>1722</dateF>
    <f1>90</f1>
    <f2>215</f2>
    <f3>276</f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>100</atl>
    <mf>39</mf>
    <ID>P79</ID>
    <cID>C400</cID>
    <aID>MR1E0</aID>
    <contenu>Coupe de bois.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>7</f1>
    <f2>39</f2>
    <f3>131</f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>101</atl>
    <mf>40</mf>
    <ID>P79</ID>
    <cID>C401</cID>
    <aID>MR1E1</aID>
    <contenu>Coupe de bois.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>275</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>101</atl>
    <mf>40</mf>
    <ID>P79</ID>
    <cID>C402</cID>
    <aID>MR1E1</aID>
    <contenu>Entendra les officiers municipaux de Rochefort au sujet de la demande qui leur est faite de 72 lits militaires.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>275</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>101</atl>
    <mf>40</mf>
    <ID>P79</ID>
    <cID>C402</cID>
    <aID>MR1E1</aID>
    <contenu>Entendra les officiers municipaux de Rochefort au sujet de la demande qui leur est faite de 72 lits militaires.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>384</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>101</atl>
    <mf>40</mf>
    <ID>P79</ID>
    <cID>C402</cID>
    <aID>MR1E1</aID>
    <contenu>Entendra les officiers municipaux de Rochefort au sujet de la demande qui leur est faite de 72 lits militaires.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>384</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>101</atl>
    <mf>40</mf>
    <ID>P79</ID>
    <cID>C402</cID>
    <aID>MR1E1</aID>
    <contenu>Entendra les officiers municipaux de Rochefort au sujet de la demande qui leur est faite de 72 lits militaires.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>581</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>101</atl>
    <mf>40</mf>
    <ID>P79</ID>
    <cID>C410</cID>
    <aID>MR1E1</aID>
    <contenu>Écrit au Conseil au sujet de la tour des Baleines, île de Ré.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>581</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>101</atl>
    <mf>40</mf>
    <ID>P79</ID>
    <cID>C410</cID>
    <aID>MR1E1</aID>
    <contenu>Écrit au Conseil au sujet de la tour des Baleines, île de Ré.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>581</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>101</atl>
    <mf>40</mf>
    <ID>P79</ID>
    <cID>C410</cID>
    <aID>MR1E1</aID>
    <contenu>Écrit au Conseil au sujet de la tour des Baleines, île de Ré.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>581</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>101</atl>
    <mf>40</mf>
    <ID>P79</ID>
    <cID>C410</cID>
    <aID>MR1E1</aID>
    <contenu>Écrit au Conseil au sujet de la tour des Baleines, île de Ré.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>787</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>101</atl>
    <mf>40</mf>
    <ID>P79</ID>
    <cID>C410</cID>
    <aID>MR1E1</aID>
    <contenu>Écrit au Conseil au sujet de la tour des Baleines, île de Ré.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>787</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>101</atl>
    <mf>40</mf>
    <ID>P79</ID>
    <cID>C410</cID>
    <aID>MR1E1</aID>
    <contenu>Écrit au Conseil au sujet de la tour des Baleines, île de Ré.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>787</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>101</atl>
    <mf>40</mf>
    <ID>P79</ID>
    <cID>C410</cID>
    <aID>MR1E1</aID>
    <contenu>Écrit au Conseil au sujet de la tour des Baleines, île de Ré.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>787</f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>101</atl>
    <mf>40</mf>
    <ID>P79</ID>
    <cID>C410</cID>
    <aID>MR1E1</aID>
    <contenu>Écrit au Conseil au sujet de la tour des Baleines, île de Ré.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>4</f1>
    <f2>103</f2>
    <f3>193</f3>
    <f4>352</f4>
    <f5>385</f5>
    <f6>519</f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>102</atl>
    <mf>40</mf>
    <ID>P79</ID>
    <cID>C410</cID>
    <aID>MR1E2</aID>
    <contenu>Écrit au Conseil au sujet de la tour des Baleines, île de Ré.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>4</f1>
    <f2>103</f2>
    <f3>193</f3>
    <f4>352</f4>
    <f5>385</f5>
    <f6>519</f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>102</atl>
    <mf>40</mf>
    <ID>P79</ID>
    <cID>C410</cID>
    <aID>MR1E2</aID>
    <contenu>Écrit au Conseil au sujet de la tour des Baleines, île de Ré.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>4</f1>
    <f2>103</f2>
    <f3>193</f3>
    <f4>352</f4>
    <f5>385</f5>
    <f6>519</f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>102</atl>
    <mf>40</mf>
    <ID>P79</ID>
    <cID>C410</cID>
    <aID>MR1E2</aID>
    <contenu>Écrit au Conseil au sujet de la tour des Baleines, île de Ré.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>4</f1>
    <f2>103</f2>
    <f3>193</f3>
    <f4>352</f4>
    <f5>385</f5>
    <f6>519</f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>102</atl>
    <mf>40</mf>
    <ID>P79</ID>
    <cID>C410</cID>
    <aID>MR1E2</aID>
    <contenu>Écrit au Conseil au sujet de la tour des Baleines, île de Ré.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>42</f1>
    <f2>87</f2>
    <f3>133</f3>
    <f4>171</f4>
    <f5>175</f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>A</serie>
    <ssserie></ssserie>
    <atl>8</atl>
    <mf></mf>
    <ID>P79</ID>
    <cID>C410</cID>
    <aID>MR1A8</aID>
    <contenu>Écrit au Conseil au sujet de la tour des Baleines, île de Ré.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>42</f1>
    <f2>87</f2>
    <f3>133</f3>
    <f4>171</f4>
    <f5>175</f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>A</serie>
    <ssserie></ssserie>
    <atl>8</atl>
    <mf></mf>
    <ID>P79</ID>
    <cID>C410</cID>
    <aID>MR1A8</aID>
    <contenu>Écrit au Conseil au sujet de la tour des Baleines, île de Ré.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>42</f1>
    <f2>87</f2>
    <f3>133</f3>
    <f4>171</f4>
    <f5>175</f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>A</serie>
    <ssserie></ssserie>
    <atl>8</atl>
    <mf></mf>
    <ID>P79</ID>
    <cID>C410</cID>
    <aID>MR1A8</aID>
    <contenu>Écrit au Conseil au sujet de la tour des Baleines, île de Ré.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1723</dateD>
    <dateF>1723</dateF>
    <f1>42</f1>
    <f2>87</f2>
    <f3>133</f3>
    <f4>171</f4>
    <f5>175</f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>A</serie>
    <ssserie></ssserie>
    <atl>8</atl>
    <mf></mf>
    <ID>P79</ID>
    <cID>C410</cID>
    <aID>MR1A8</aID>
    <contenu>Écrit au Conseil au sujet de la tour des Baleines, île de Ré.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1724</dateD>
    <dateF>1724</dateF>
    <f1>140 verso </f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>L</serie>
    <ssserie>1</ssserie>
    <atl>4</atl>
    <mf></mf>
    <ID>P79</ID>
    <cID>C407</cID>
    <aID>MR1L14</aID>
    <contenu>Juge l’affaire de l’apposition des scellés après le décès du Sieur Bernicot.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1724</dateD>
    <dateF>1724</dateF>
    <f1>140 verso </f1>
    <f2></f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>L</serie>
    <ssserie>1</ssserie>
    <atl>4</atl>
    <mf></mf>
    <ID>P79</ID>
    <cID>C407</cID>
    <aID>MR1L14</aID>
    <contenu>Juge l’affaire de l’apposition des scellés après le décès du Sieur Bernicot.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1724</dateD>
    <dateF>1724</dateF>
    <f1>319</f1>
    <f2>423</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>103</atl>
    <mf>41</mf>
    <ID>P79</ID>
    <cID>C407</cID>
    <aID>MR1E3</aID>
    <contenu>Juge l’affaire de l’apposition des scellés après le décès du Sieur Bernicot.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1724</dateD>
    <dateF>1724</dateF>
    <f1>319</f1>
    <f2>423</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>103</atl>
    <mf>41</mf>
    <ID>P79</ID>
    <cID>C407</cID>
    <aID>MR1E3</aID>
    <contenu>Juge l’affaire de l’apposition des scellés après le décès du Sieur Bernicot.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1725</dateD>
    <dateF>1725</dateF>
    <f1>45</f1>
    <f2>181</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>
    <f10></f10>
    <f11></f11>
    <f12></f12>
    <f13></f13>
    <f14></f14>
    <f15></f15>
    <f16></f16>
    <f17></f17>
    <f18></f18>
    <f19></f19>
    <f20></f20>
    <f21></f21>
    <f22></f22>
    <f23></f23>
    <f24></f24>
    <f25></f25>
    <sserie>1</sserie>
    <serie>E</serie>
    <ssserie></ssserie>
    <atl>105</atl>
    <mf>42</mf>
    <ID>P79</ID>
    <cID>C408</cID>
    <aID>MR1E5</aID>
    <contenu>Juge l’affaire de l’apposition des scellés après le décès du Sieur Bernicot.</contenu>
    <tome>6</tome>
    <page>2</page>
  </DATA_RECORD>
  <DATA_RECORD>
    <function>Personne</function>
    <unittitle>Amelot de Chaillou</unittitle>
    <dateD>1725</dateD>
    <dateF>1725</dateF>
    <f1>45</f1>
    <f2>181</f2>
    <f3></f3>
    <f4></f4>
    <f5></f5>
    <f6></f6>
    <f7></f7>
    <f8></f8>
    <f9></f9>